-- this script wasn't pasted and minifying this won't make anyone stop pasting this :::::::))))))))) ok! i don't caRE!! pls do paste this i need more attention!!






do
local a;a=hookmetamethod(game,"__namecall",function(b,...)
local c=getnamecallmethod()

if b.Name=="HaIIoooooooooooo"or b.Name=="Boogers"then
if c=="FireServer"
or c=="FireUnreliable"
or c=="InvokeServer"then
return nil
end
end

return a(b,...)
end)
end

local a=clonefunction(Instance.new)
local b=clonefunction(game.GetService)
clonefunction(game.IsLoaded)
local c=clonefunction(game.Clone)
clonefunction(game.Destroy)
local d=clonefunction(game.Remove)
local e=clonefunction(game.GetChildren)
clonefunction(game.ClearAllChildren)
clonefunction(game.GetDescendants)
local f=clonefunction(game.IsDescendantOf)
clonefunction(game.IsA)
local g=clonefunction(game.FindFirstChild)
local h=clonefunction(game.WaitForChild)

local i=clonefunction(game.FindFirstChildOfClass)
clonefunction(game.HttpGet)
clonefunction(game.GetPropertyChangedSignal)
local j=clonefunction(game.GetAttribute)

local k=clonefunction(b(game,"Players").GetPlayers)
local l=clonefunction(b(game,"Players").GetPlayerFromCharacter)
clonefunction(b(game,"Players").CreateHumanoidModelFromUserId)
clonefunction(b(game,"Stats").Network.ServerStatsItem["Data Ping"].GetValue)
clonefunction(b(game,"UserInputService").GetMouseLocation)
local m=clonefunction(b(game,"UserInputService").IsKeyDown)
clonefunction(b(game,"UserInputService").IsMouseButtonPressed)
clonefunction(b(game,"UserInputService").GetFocusedTextBox)
clonefunction(b(game,"TextService").GetTextSize)
local n=clonefunction(b(game,"TextService").GetTextBoundsAsync)
clonefunction(a"VirtualInputManager".SendMouseButtonEvent)
clonefunction(a"VirtualInputManager".SendMouseMoveDeltaEvent)
clonefunction(b(game,"Teams").GetTeams)
clonefunction(b(game,"Players").LocalPlayer.GetMouse)

clonefunction(b(game,"RunService").RenderStepped.Wait)
clonefunction(a"BindableEvent".Fire)

local o=clonefunction(CFrame.new)
local p=clonefunction(CFrame.Angles)
local q=clonefunction(CFrame.lookAt)
clonefunction(o().Lerp)
local r=clonefunction(o().GetComponents)
clonefunction(o().PointToObjectSpace)
clonefunction(o().ToObjectSpace)
clonefunction(o().ToEulerAnglesXYZ)

local s=clonefunction(Vector3.new)
clonefunction(s().Lerp)

local t=clonefunction(Vector2.new)

local u=clonefunction(UDim2.new)
local v=clonefunction(UDim2.fromOffset)
clonefunction(UDim2.fromScale)
local w=clonefunction(UDim.new)

local x=clonefunction(Color3.new)
local y=clonefunction(Color3.fromRGB)
clonefunction(Color3.fromHSV)
clonefunction(Color3.toHSV)
clonefunction(x().ToHex)
clonefunction(Color3.fromHex)

local z=clonefunction(ColorSequence.new)
local A=clonefunction(ColorSequenceKeypoint.new)
local B=clonefunction(NumberSequence.new)
local C=clonefunction(NumberSequenceKeypoint.new)

clonefunction(Ray.new)
local D=clonefunction(RaycastParams.new)
local E=clonefunction(workspace.Raycast)

clonefunction(string.format)
local F=clonefunction(string.upper)
local G=clonefunction(string.lower)
local H=clonefunction(string.find)
clonefunction(string.len)
clonefunction(string.gsub)
clonefunction(string.sub)
clonefunction(string.match)
clonefunction(string.gmatch)
clonefunction(string.split)
clonefunction(tostring)

local I=clonefunction(table.insert)
local J=clonefunction(table.clear)
local K=clonefunction(table.remove)
clonefunction(table.find)
local L=clonefunction(table.sort)
clonefunction(table.concat)
local M=clonefunction(table.unpack)
clonefunction(table.pack)

clonefunction(table.clone)
local N=clonefunction(select)

local O=clonefunction(math.clamp)
clonefunction(math.random)
local P=clonefunction(math.rad)
local Q=clonefunction(math.floor)
clonefunction(math.abs)
local R=clonefunction(math.max)
local S=clonefunction(math.min)
local T=clonefunction(math.sin)
local U=clonefunction(math.cos)
clonefunction(math.deg)
clonefunction(math.ceil)
clonefunction(math.atan2)
clonefunction(math.sqrt)
local V=clonefunction(math.pow)
local W=clonefunction(math.round)

local X=1e309

clonefunction(tonumber)

local Y=function(Y,Z,_)
return Y+(Z-Y)*_
end

clonefunction(debug.traceback)

local Z=clonefunction(tick)
clonefunction(os.date)
clonefunction(os.time)
local _=clonefunction(os.clock)

local aa=clonefunction(a"Camera".WorldToViewportPoint)
clonefunction(a"Camera".WorldToScreenPoint)
clonefunction(a"Humanoid".ChangeState)
local ab=clonefunction(a"Humanoid".GetState)
clonefunction(a"Humanoid".SetStateEnabled)

clonefunction(a"Model".GetModelSize)

clonefunction(a"Player".Kick)

clonefunction(require)
clonefunction(type)
local ac=clonefunction(typeof)
clonefunction(coroutine.wrap)
local ad=clonefunction(task.wait)
clonefunction(pcall)
clonefunction(wait)
local ae=clonefunction(task.spawn)
local af=clonefunction(task.delay)
clonefunction(task.defer)
clonefunction(task.cancel)
local ag=clonefunction(workspace.GetServerTimeNow)

local ah=clonefunction(game.IsA)

local ai=cloneref(b(game,"HttpService"))
local aj=cloneref(b(game,"Lighting"))
local ak=cloneref(b(game,"TweenService"))
local al=cloneref(b(game,"Workspace"))
local am=cloneref(b(game,"RunService"))
local an=cloneref(b(game,"TextService"))
local ao=cloneref(b(game,"UserInputService"))
local ap=cloneref(b(game,"ReplicatedStorage"))

local aq=cloneref(b(game,"Players"))
local ar=aq.LocalPlayer

local as=gethui()or g(cloneref(b(game,"CoreGui")),"RobloxGui",true)
local at=s()
local au={X=math.sqrt(-1),Y=math.sqrt(-1),Z=math.sqrt(-1)}
local av=al.CurrentCamera

local aw=function(aw,...)
ae(function(...)
local ax=coroutine.create(aw);
coroutine.resume(ax,...);
end,...);
end
local ax=function(ax,ay,...)
local az=ay;ay=function(...)
setthreadidentity(ax)
return az(...)
end;

ae(function(...)
local aA=coroutine.create(ay)
coroutine.resume(aA,...)
end,...)
end
local function GetFileName(ay)
return ay:match"[^/\\]+$"
end
local function GetFilesName(ay)
local az={}
for aA,aB in ay do
az[aA]=GetFileName(aB)
end
return az
end

local ay={TextCache=
{},HitPartCache=
{},ViewmodelOffsetX=
0,ViewmodelOffsetY=
0,ViewmodelOffsetZ=
0,ViewmodelOffsetRoll=
0,ViewmodelOffsetYaw=
0,ViewmodelOffsetPitch=
0,RaycastParameter=

D(),RageBotCache=
{Entities=
{},RaycastResults=
{},LastCleanup=
0,Enemies=
{},LastEnemyUpdate=
0,OriginCache=
{},LastThink=
0,RaycastParams=
RaycastParams.new()
},FadeHitmarker=
TweenInfo.new(1,Enum.EasingStyle.Exponential,Enum.EasingDirection.Out),
}
ay.RaycastParameter.FilterType=Enum.RaycastFilterType.Exclude
ay.RaycastParameter.FilterDescendantsInstances={Character}
ay.RaycastParameter.IgnoreWater=true
local az={}

do
local aA=function(aA,aB)
writefile(aA..".ttf",aB)

local aC={
Name=aA,
faces={
{
name="Regular",
weight=400,
style="normal",
assetId=getcustomasset(aA..".ttf")
}
}
}

writefile(aA..".json",ai:JSONEncode(aC))
return Font.new(getcustomasset(aA..".json"),Enum.FontWeight.Regular)
end

az={
Tahoma=aA("tahoma",game:HttpGet"https://github.com/mental1illness/storage/raw/refs/heads/main/fonts/old-tahoma.ttf"),
TahomaBold=aA("tahomabold",game:HttpGet"https://github.com/mental1illness/storage/raw/refs/heads/main/fonts/old-tahoma-bold.ttf"),
SmallestPixel7=aA("smallestpixel7",game:HttpGet"https://github.com/mental1illness/storage/raw/refs/heads/main/fonts/smallest_pixel-7.ttf"),
ProggyClean=aA("proggyclean",game:HttpGet"https://github.com/mental1illness/storage/raw/refs/heads/main/fonts/proggyclean.ttf"),
Minecraftia=aA("minecraftia",game:HttpGet"https://github.com/mental1illness/storage/raw/refs/heads/main/fonts/Minecraftia-Regular.ttf")
}
end

local aA={
[0]="Tahoma",
[1]="TahomaBold",
[2]="Verdana",
[3]="VerdanaBold",
[4]="SmallestPixel7",
[5]="ProggyClean",
[6]="Minecraftia",
}

local aB=function(aB)
if ac(aB)~="number"then return nil end
local aC=aA[aB]
if not aC then return nil end
return az[aC]
end

local aC=function(aC,aD)
if ah(aC,"Frame")and aD=="Circle"then
aC.BorderSizePixel=0
aC.BackgroundColor3=y(255,255,255)
aC.Size=u(0,200,0,200)
aC.ClipsDescendants=false

local aE=a"UICorner"
aE.CornerRadius=w(1,0)
aE.Parent=aC

elseif ah(aC,"Frame")then
aC.BorderSizePixel=0
aC.BackgroundColor3=y(255,255,255)
aC.Size=u(0,200,0,200)
aC.ClipsDescendants=false

elseif ah(aC,"TextLabel")then
aC.BackgroundTransparency=1
aC.TextSize=12
aC.FontFace=az.Tahoma
aC.TextColor3=y(255,255,255)
aC.ClipsDescendants=false
elseif ah(aC,"ScreenGui")then
aC.IgnoreGuiInset=true
aC.ResetOnSpawn=false
end
end

local aD={
SetRenderProperty=function(aD,aE,aF)
if aD and aD[aE]~=nil then
if aE=="Font"then
aE="FontFace"
end

if aE=="FontFace"and ac(aF)=="number"then
aF=aB(aF)
end

local aG=aD[aE]

if ac(aG)=="EnumItem"then
aF=aG.EnumType[aF]
end

aD[aE]=aF
end

return aD
end,
GetRenderProperty=function(aD,aE)
if aD then
return aD[aE]
end
return nil
end,
DestroyRenderObject=function(aD)
if aD and aD.Remove then
d(aD)
else
return false
end
return true
end,
new=function(aD,aE)
local aF
if aD=="Circle"then
aD="Frame"
aF="Circle"
end
local aG=a(aD)
aE=aE or{}
aC(aG,aF)

for aH,aI in aE do
pcall(function()
if aH=="Font"then
aH="FontFace"
end

if aH=="FontFace"and ac(aI)=="number"then
aI=aB(aI)
end

local aJ=aG[aH]

if ac(aJ)=="EnumItem"then
aI=aJ.EnumType[aI]
end

aG[aH]=aI
ay[aH]=aI
end)
end

return aG
end,

Fonts={
Tahoma=0,
TahomaBold=1,
Verdana=2,
VerdanaBold=3,
SmallestPixel7=4,
ProggyClean=5,
Minecraftia=6
}
}

local aE={ToUse=
{HitPart=
g(ap.Events,"HitParl"),ReplicateAnimations=
g(ap.Events,"ReplicateAnimation"),ReplicateSound=
g(ap.Events,"ReplicateSound")
}
}

local aF={Guns=
c(g(ap,"Weapons")),
}

local aG={LastHit=
nil,RageBot=
{Functions=
{
},CurrentTarget=
nil,LastRageBotFired=
0,TimeOffset=
{Last=
0,LastChanged=
_(),
},TimeOffset2=
{Last=
0,LastChanged=
_(),
},CanRage=
true,CanKillAll=
true
},Backtrack=
{Records=
{}
},ForwardTrack=
{Records=
{}
},Misc=
{Functions=
{

},
},Visuals=
{Functions=
{

},States=
{ThirdPerson=
"",
}
},Esp=
{Entities=
{

},SettingsCache=
{TextCases=
{

},TweenInformation=
{
[1]=TweenInfo.new(1,Enum.EasingStyle.Exponential,Enum.EasingDirection.Out)
}
},TextOffsets=
{SmallestPixel7=

{
X=0,
Y=0,Side=
{Bottom=
{X=0,Y=-2},Left=
{X=-1,Y=0},Right=
{X=0,Y=0}
}
},Minecraftia=
{
X=0,
Y=-3,Side=
{Bottom=
{X=0,Y=-6},Left=
{X=-1,Y=-5},Right=
{X=-1,Y=-5}
}
},Tahoma=
{
X=0,
Y=1,Side=
{Bottom=
{X=0,Y=-2},Left=
{X=-1,Y=0},Right=
{X=-1,Y=0}
}
},TahomaBold=
{
X=0,
Y=1,Side=
{Bottom=
{X=0,Y=-2},Left=
{X=-1,Y=0},Right=
{X=-1,Y=0}
}
},Verdana=
{
X=0,
Y=1,Side=
{Bottom=
{X=0,Y=-2},Left=
{X=-1,Y=0},Right=
{X=-1,Y=0}
}
},VerdanaBold=
{
X=0,
Y=1,Side=
{Bottom=
{X=0,Y=-2},Left=
{X=-1,Y=0},Right=
{X=-1,Y=0}
}
},ProggyClean=
{
X=0,
Y=0,Side=
{Bottom=
{X=0,Y=-2},Left=
{X=1,Y=-3},Right=
{X=1,Y=-3}
}
},
},Holder=
aD.new("ScreenGui",{Parent=as}),Holder2=
aD.new("ScreenGui",{Parent=as}),
},Utility=
{
GetTeam=function(aG)
local aH=aG.Team
if aH~=nil then
return aH
end
return j(aG,"Team")
end,
GetTransparency=function(aG)
if aG and aG.IsA then
if aG.ClassName=="UIStroke"then
return"Transparency"
elseif aG.ClassName=="Frame"then
return"BackgroundTransparency"
elseif aG.ClassName=="TextLabel"then
return"TextTransparency"
elseif aG.ClassName=="ImageLabel"then
return"ImageTransparency"
end
end
end,
GetTextBounds=function(aG,aH,aI,aJ)
local aK=aG.."|"..tostring(aH).."|"..tostring(aI).."|"..tostring(aJ)
local aL=ay.TextCache[aK]
if aL then
return aL.X,aL.Y
end
local aM=a"GetTextBoundsParams"
aM.Text=aG
aM.RichText=true
aM.Font=aH
aM.Size=aI
aM.Width=aJ or al.CurrentCamera.ViewportSize.X-32

local aN=n(an,aM)
ay.TextCache[aK]={X=aN.X,Y=aN.Y}
return aN.X,aN.Y
end,
GetNilsForRemote=function(aG)
if aG=="HitPart"then
return nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil
end
end,
EncodePosition=function(aG)
return s(((aG.X-156325)*13+17854)*16,(aG.Y+64000)*7-142657,(aG.Z*9-47000)*6)
end,
DecodePosition=function(aG)
return s(((aG.X/16)-17854)/13+156325,((aG.Y+142657)/7)-64000,(aG.Z/6+47000)/9)
end,
IsJumpingOrFalling=function()
local aG=ar.Character
if not aG then return false end

local aH=i(aG,"Humanoid")
if not aH then return false end

local aI=ab(aH)

return aI==Enum.HumanoidStateType.Jumping or aI==Enum.HumanoidStateType.Freefall
end,
GetWeaponReference=function(aG)
if ac(aG)=="Instance"and g(aG,"CopyFrom")then
return aG.CopyFrom.Value
else
return aG
end
end,
},Constants=

{EasingStyles=
{
"Linear",
"Sine",
"Back",
"Quad",
"Quart",
"Quint",
"Bounce",
"Elastic",
"Exponential",
"Circular",
"Cubic"
},MaterialMultipliers=
{
[Enum.Material.DiamondPlate]=3,
[Enum.Material.CorrodedMetal]=2,
[Enum.Material.Metal]=2,
[Enum.Material.Concrete]=2,
[Enum.Material.Brick]=2,
[Enum.Material.Wood]=0.1,
[Enum.Material.WoodPlanks]=0.1,
},Debris=
g(al,"Debris"),RayIgnore=
g(al,"Ray_Ignore"),Status=
g(al,"Status"),SoundsIndex=
{
"AR2 Head",
"AR2 Body",
"AR2 Limb",
"BB HitM",
"BB Kill",
"PD Head",
"PD Body",
"Neverlose",
"Gamesense",
"Baimware",
"Steve",
"Skeet",
"Body",
"Ding",
"Mario",
"Mario 2",
"Minecraft",
"Among Us",
"Button",
"Oof",
"Osu",
"Osu Combobreak",
"Bambi",
"Click",
"Snow",
"Stone",
"Rust",
"Splat",
"Bell",
"Slime",
"Saber",
"Bat",
"Bubble",
"Pick",
"Pop",
"EmptyGun",
"Bamboo",
"Stomp",
"Bag",
"HitMarker",
"LaserSlash",
"RailGunF",
"Bruh",
"Crit",
"Bonk",
"Clink",
"CoD",
"Lazer Beam",
"Windows XP Error",
"Windows XP Ding",
"HL Med Kit",
"HL Door",
"HL Crowbar",
"HL Revolver",
"HL Elevator",
"TF2 HitSound",
"TF2 Squasher",
"TF2 Retro",
"TF2 Space",
"TF2 Vortex",
"TF2 Beepo",
"TF2 Bat",
"TF2 Pow",
"TF2 You Suck",
"Quake Hitsound",
"Fart",
"Fart2",
"FortniteGuns",
"Crickets",
"ScreamingKid",
"BitchBot",
"BitchBot Head",
"BitchBot Body",
"Minecraft Experience ",
"BameWare",
"Fatality",
"Fatality MKX",
"Fatality Original",
"Doublekill 1",
"Doublekill 2",
"Killing Spree 1",
"Killing Spree 2",
"Sit Dog",
"Csgo",
"Bop",
"Grenade Hit",
"KillTrocity",
"Double Kill",
"Triple kill",
"Over Kill",
"Kill Tacular",
"Kill Imanjaro",
"Kill Tastrophe",
"Kill Pocalypse",
"Kill Ionaire",
"Killing Spree",
"Killing Frenzy",
"Carrier Kill",
"Clutch Kill",
"Taco Bell",
"Kombat",
"Headshot",
"Elevator",
},Hitboxes=
{HeadHB=
true,Head=
true,UpperTorso=

true,LowerTorso=
true,LeftUpperArm=

true,LeftLowerArm=
true,LeftHand=
true,RightUpperArm=

true,RightLowerArm=
true,RightHand=
true,LeftUpperLeg=

true,LeftLowerLeg=
true,LeftFoot=
true,RightUpperLeg=

true,RightLowerLeg=
true,RightFoot=
true,
},Sounds=
{
["AR2 Head"]="2062016772",
["AR2 Body"]="2062015952",
["AR2 Limb"]="6659353525",
["BB HitM"]="4645745735",
["BB Kill"]="2636743632",
["PD Head"]="4585351098",
["PD Body"]="4585364605",Neverlose=
"8726881116",Gamesense=
"4817809188",Baimware=
"3124331820",Steve=
"4965083997",Skeet=
"4753603610",Body=
"3213738472",Ding=
"7149516994",Mario=
"2815207981",
["Mario 2"]="5709456554",Minecraft=
"6361963422",
["Among Us"]="5700183626",Button=
"12221967",Oof=
"4792539171",Osu=
"7149919358",
["Osu Combobreak"]="3547118594",Bambi=
"8437203821",Click=
"8053704437",Snow=
"6455527632",Stone=
"3581383408",Rust=
"1255040462",Splat=
"12222152",Bell=
"6534947240",Slime=
"6916371803",Saber=
"8415678813",Bat=
"3333907347",Bubble=
"6534947588",Pick=
"1347140027",Pop=
"198598793",EmptyGun=
"203691822",Bamboo=
"3769434519",Stomp=
"200632875",Bag=
"364942410",HitMarker=
"8543972310",LaserSlash=
"199145497",RailGunF=
"199145534",Bruh=
"4275842574",Crit=
"296102734",Bonk=
"3765689841",Clink=
"711751971",CoD=
"160432334",
["Lazer Beam"]="130791043",
["Windows XP Error"]="160715357",
["Windows XP Ding"]="489390072",
["HL Med Kit"]="4720445506",
["HL Door"]="4996094887",
["HL Crowbar"]="546410481",
["HL Revolver"]="1678424590",
["HL Elevator"]="237877850",
["TF2 HitSound"]="3455144981",
["TF2 Squasher"]="3466981613",
["TF2 Retro"]="3466984142",
["TF2 Space"]="3466982899",
["TF2 Vortex"]="3466980212",
["TF2 Beepo"]="3466987025",
["TF2 Bat"]="3333907347",
["TF2 Pow"]="679798995",
["TF2 You Suck"]="1058417264",
["Quake Hitsound"]="4868633804",Fart=
"131314452",Fart2=
"6367774932",FortniteGuns=
"3008769599",Crickets=
"2101148",ScreamingKid=
"5980352978",BitchBot=
"5709456554",
["BitchBot Head"]="5043539486",
["BitchBot Body"]="3744371342",
["Minecraft Experience "]="1053296915",BameWare=
"7898991882",Fatality=
"7347423703",
["Fatality MKX"]="6721975770",
["Fatality Original"]="158012252",
["Doublekill 1"]="1950547222",
["Doublekill 2"]="130819307",
["Killing Spree 1"]="723054723",
["Killing Spree 2"]="937898383",
["Sit Dog"]="7349055654",Csgo=
"7269900245",Bop=
"8829676038",
["Grenade Hit"]="5684745272",KillTrocity=
"6818544945",
["Double Kill"]="6818527307",
["Triple kill"]="6818526855",
["Over Kill"]="6818526995",
["Kill Tacular"]="6818527070",
["Kill Imanjaro"]="6818527258",
["Kill Tastrophe"]="6818526916",
["Kill Pocalypse"]="6818527144",
["Kill Ionaire"]="6818527200",
["Killing Spree"]="6822465178",
["Killing Frenzy"]="6822465319",
["Carrier Kill"]="7139067012",
["Clutch Kill"]="7379106527",
["Taco Bell"]="5689199277",Kombat=
"8527433497",Headshot=
"8418469749",Elevator=
"8322227967",
}
},Assets=
{Images=
{Girls=
{Rem=
"https://github.com/mental1illness/flohaxx-storage/blob/main/images/Rem.png?raw=true",Aiko=
"https://github.com/mental1illness/flohaxx-storage/blob/main/images/Aiko.png?raw=true",
}
}
},ClientScript=
getsenv(h(ar.PlayerGui,"Client")),GarbageCollector=
{},MainScreenGui=
aD.new("ScreenGui",{Parent=as})
}

for aH,aI in getgc(true)do
local aJ=ac(aI)
if aJ=="table"then
if rawget(aI,"ammocount")then
aG.GarbageCollector.StatusTable=aI
end
end
end

for aH,aI in aG.Assets.Images.Girls do
if aH and aI then
writefile(aH..".png",game:HttpGet(aI))
aG.Assets.Images.Girls[aH]=getcustomasset(aH..".png")

end
end

pcall(function()setfflag("AdornShadingAPI","true")end)

local aH=getgenv and getgenv()local aI=
getrenv or getfenv()

local aJ,aK=loadstring(game:HttpGet"https://raw.githubusercontent.com/wristslashing1337/host/refs/heads/main/ui.luau")()
local aL=aJ.Flags
local aM=loadstring(game:HttpGet"https://raw.githubusercontent.com/mental1illness/modules/refs/heads/main/Signals.lua")()
local aN={EspChanged=
aM.new(),
}
local aO={Events=
{HitPlayer=
aM.new(),KillPlayer=
aM.new(),
},RageBot=
{TargetChanged=
aM.new(),Fired=
aM.new(),
}
}

local aP={Hitmarker={}}

do
do
local aQ=aD.new("Frame",{
BorderColor3=y(0,0,0),
Parent=aG.MainScreenGui,
Rotation=45,
Name="Hitmarker",
BackgroundTransparency=1,
Position=UDim2.fromScale(0.5,0.5),
AnchorPoint=t(0.5,0.5),
Size=v(25,26),
BorderSizePixel=0,
BackgroundColor3=y(255,255,255),
})

local aR=aD.new("Frame",{
AnchorPoint=t(0.5,0),
Parent=aQ,
Name="Frame2",
Position=UDim2.fromScale(0.5,0),
BorderColor3=y(0,0,0),
Size=v(1,10),
BorderSizePixel=0,
BackgroundColor3=y(255,255,255),
})

local aS=aD.new("Frame",{
AnchorPoint=t(0,0.5),
Parent=aQ,
Name="Frame3",
Position=UDim2.fromScale(0,0.5),
BorderColor3=y(0,0,0),
Size=v(10,1),
BorderSizePixel=0,
BackgroundColor3=y(255,255,255),
})

local aT=aD.new("Frame",{
AnchorPoint=t(1,0.5),
Parent=aQ,
Name="Frame4",
Position=UDim2.fromScale(1,0.5),
BorderColor3=y(0,0,0),
Size=v(10,1),
BorderSizePixel=0,
BackgroundColor3=y(255,255,255),
})

local aU=aD.new("Frame",{
AnchorPoint=t(0.5,1),
Parent=aQ,
Position=UDim2.fromScale(0.5,1),
BorderColor3=y(0,0,0),
Size=v(1,10),
BorderSizePixel=0,
BackgroundColor3=y(255,255,255),
})

aD.new("ImageLabel",{
Parent=aU,
Name="Glow",
ImageColor3=y(255,255,255),
ScaleType="Slice",
ImageTransparency=0.8999999761581421,
BorderColor3=y(0,0,0),
BackgroundColor3=y(255,255,255),
Image="http://www.roblox.com/asset/?id=18245826428",
BackgroundTransparency=1,
Position=u(0,-20,0,-20),
Size=u(1,40,0,42),
ZIndex=2,
BorderSizePixel=0,
SliceCenter=Rect.new(t(21,21),t(79,79))
})
aD.new("ImageLabel",{
Parent=aT,
Name="Glow",
ImageColor3=y(255,255,255),
ScaleType="Slice",
ImageTransparency=0.8999999761581421,
BorderColor3=y(0,0,0),
BackgroundColor3=y(255,255,255),
Image="http://www.roblox.com/asset/?id=18245826428",
BackgroundTransparency=1,
Position=u(0,-20,0,-20),
Size=u(1,40,0,42),
ZIndex=2,
BorderSizePixel=0,
SliceCenter=Rect.new(t(21,21),t(79,79))
})
aD.new("ImageLabel",{
Parent=aS,
Name="Glow",
ImageColor3=y(255,255,255),
ScaleType="Slice",
ImageTransparency=0.8999999761581421,
BorderColor3=y(0,0,0),
BackgroundColor3=y(255,255,255),
Image="http://www.roblox.com/asset/?id=18245826428",
BackgroundTransparency=1,
Position=u(0,-20,0,-20),
Size=u(1,40,0,42),
ZIndex=2,
BorderSizePixel=0,
SliceCenter=Rect.new(t(21,21),t(79,79))
})
aD.new("ImageLabel",{
Parent=aR,
Name="Glow",
ImageColor3=y(255,255,255),
ScaleType="Slice",
ImageTransparency=0.8999999761581421,
BorderColor3=y(0,0,0),
BackgroundColor3=y(255,255,255),
Image="http://www.roblox.com/asset/?id=18245826428",
BackgroundTransparency=1,
Position=u(0,-20,0,-20),
Size=u(1,40,0,42),
ZIndex=2,
BorderSizePixel=0,
SliceCenter=Rect.new(t(21,21),t(79,79))
})

aP.Hitmarker.Holder=aQ
aP.Hitmarker.Line1=aU
aP.Hitmarker.Line2=aR
aP.Hitmarker.Line3=aS
aP.Hitmarker.Line4=aT

for aV,aW in aP.Hitmarker do
aD.SetRenderProperty(aW,"BackgroundTransparency",1)
if g(aW,"Glow")then
aD.SetRenderProperty(aW.Glow,"ImageTransparency",1)
end
end
end
end

local aQ=aJ:Window{name="Menu"}
local aR={
[1]={
Name="RageBot",
Object=aQ:Tab{name="Rage"}
},
[2]={
Name="Misc",
Object=aQ:Tab{name="Misc"}
},
[3]={
Name="ESP",
Object=aQ:Tab{name="Esp"}
},
[4]={
Name="Visuals",
Object=aQ:Tab{name="Visuals"}
},
[5]={
Name="Extra",
Object=aQ:Tab{name="Extra"}
}
}
local aS={
[1]={
Name="RageBot",
Left=aR[1].Object:Column(),
Right=aR[1].Object:Column()
},
[2]={
Name="Misc",
Left=aR[2].Object:Column(),
Right=aR[2].Object:Column()
},
[3]={
Name="ESP",
Left=aR[3].Object:Column(),
Right=aR[3].Object:Column()
},
[4]={
Name="Visuals",
Left=aR[4].Object:Column(),
Right=aR[4].Object:Column()
},
[5]={
Name="Extra",
Left=aR[5].Object:Column(),
Right=aR[5].Object:Column()
},
}

do
aH.MamboWare=aO

aH.RobloxObj=aD
aH.RemoteEvents=aE

aH.Library=aJ
aH.Tabs=aR
aH.Columns=aS
end

do
local aT=aS[1].Left
local aU=aS[1].Right

local aV=aT:Section{Name="Main"}
local aW=aU:Section{Name="Hacker Versus Hacker"}

aV:Toggle{Name="Enabled",Flag="Rage/Enabled"}
aV:Toggle{Name="Multi Target",Flag="Rage/MultiTarget"}
aV:Toggle{Name="Use Custom Weapon",Flag="Rage/UseCustomWeapon"}
aV:Dropdown{Name="Custom Weapon List",Items={"AK-47","AWP"},Flag="Rage/CustomWeaponList",Default="AK-47"}

aV:Dropdown{Name="Fake Shoot Type",Items={"Loud","Normal","Silent"},Flag="Rage/FakeShootType",Default="Normal"}

aW:Toggle{Name="Auto Wall",Flag="Rage/AutoWall"}
aW:Slider{Name="Auto Wall Maximum Wall",Default=1,Min=1,Max=4,Flag="Rage/AutoWallMaxWalls",Interval=1}
aW:Toggle{Name="Disable Auto Wall Dmg Reduction",Flag="Rage/NoAutoWallDmgReduction"}

aW:Toggle{Name="Origin Scan",Flag="Rage/OriginScan"}
aW:Slider{Name="Origin Max Scan",Default=20,Min=1,Max=60,Flag="Rage/OriginMaxScan",Interval=1}
aW:Slider{Name="Origin Scan Radius",Default=6,Min=1,Max=20,Flag="Rage/OriginScanRadius",Interval=1}

aW:Toggle{Name="Multi Point",Flag="Rage/MultiPoint"}
aW:Slider{Name="Multi Point Scale",Default=1,Min=1,Max=6,Flag="Rage/MultiPointScale",Interval=1}

aW:Toggle{Name="Backtrack",Flag="Rage/Backtrack"}
aW:Slider{Name="Backtrack Time",Default=200,Min=1,Max=1000,Flag="Rage/BacktrackTime",Interval=1,Suffix="ms"}
aW:Toggle{Name="Forward Track",Flag="Rage/FTrack"}
aW:Slider{Name="Forward Track Time",Default=500,Min=500,Max=5000,Flag="Rage/FTrackTime",Interval=1,Suffix="ms"}
aW:Toggle{Name="Adaptive Forward Track",Flag="Rage/FTrackAdaptive"}

aV:Toggle{Name="Rapid Fire",Flag="Rage/RapidFire"}
aV:Slider{Name="Rapid Fire Tick",Default=0.1,Min=0.01,Max=0.1,Flag="Rage/RapidFireTick",Interval=0.01}

aW:Toggle{Name="Camera Resolver",Flag="Rage/CameraResolver"}
aV:Toggle{Name="Rotate Viewmodel To ",Flag="Rage/RotateVM"}
aV:Toggle{Name="Preparation Check",Flag="Rage/PrepCheck"}
aV:Toggle{Name="Time Offset",Flag="Rage/TimeOffset",Tooltip="The ragebot will target and try to shoot the player before the timer so for example if you do 300ms and when the timer reached 300ms then the ragebot will start targetting."}
aV:Slider{Name="Time Offset Value",Default=1,Min=1,Max=1000,Flag="Rage/TimeOffsetValue",Interval=1,Suffix="ms"}

end

do
local aT=aS[2].Left
local aU=aS[2].Right

local aV=aT:Section{Name="Movement"}
local aW=aT:Section{Name="Gun Modification"}
local aX=aU:Section{Name="Misc"}

aV:Toggle{Name="Speed",Flag="Misc/Speed"}
aV:Slider{Name="Speed Value",Flag="Misc/SpeedValue",Min=30,Max=900}
aV:Toggle{Name="Override Speed",Flag="Misc/OverrideSpeed"}:Keybind{Name="Override Key",Active=false,Mode="hold",Key=Enum.KeyCode.LeftShift,Flag="Misc/OverrideSpeedKey"}
aV:Slider{Name="Override Speed Value",Flag="Misc/OverrideSpeedValue",Min=30,Max=900}
aV:Toggle{Name="Auto Jump",Flag="Misc/AutoJump"}

aX:Toggle{Name="Kill All",Flag="Misc/KillAll"}
aX:Toggle{Name="Kill All Preparation Check",Flag="Misc/KillAllPrepCheck"}
aX:Toggle{Name="Kill All Time Offset",Flag="Misc/KillAllTimeOffset"}
aX:Slider{Name="Kill All Time Offset Value",Default=1,Min=1,Max=1000,Flag="Misc/KillAllTimeOffsetValue",Interval=1,Suffix="ms"}

aX:Toggle{Name="Head Shot Hit Sound",Flag="Misc/HeadHitSound"}
aX:Dropdown{Name="Head Shot Hit Sound Type",Items=aG.Constants.SoundsIndex,Flag="Misc/HeadHitSoundType",Scrolling=true}
aX:Slider{Name="Head Shot Hit Sound Volume",Default=0.5,Min=0,Max=10,Flag="Misc/HeadHitSoundVolume",Interval=0.1}
aX:Toggle{Name="Hit Sound",Flag="Misc/HitSound"}
aX:Dropdown{Name="Hit Sound Type",Items=aG.Constants.SoundsIndex,Flag="Misc/HitSoundType",Scrolling=true}
aX:Slider{Name="Hit Sound Volume",Default=0.5,Min=0,Max=10,Flag="Misc/HitSoundVolume",Interval=0.1}
aX:Toggle{Name="Kill Sound",Flag="Misc/KillSound"}
aX:Dropdown{Name="Kill Sound Type",Items=aG.Constants.SoundsIndex,Flag="Misc/KillSoundType",Scrolling=true}
aX:Slider{Name="Kill Sound Volume",Default=0.5,Min=0,Max=10,Flag="Misc/KillSoundVolume",Interval=0.1}

aX:Toggle{Name="Remove Fall Damage",Flag="Misc/NoFallDamage"}
aX:Toggle{Name="Remove Fire Damage",Flag="Misc/NoFireDamage"}

aW:Toggle{Name="Enable",Flag="Misc/GunMod"}
aW:Toggle{Name="Infinite Ammo",Flag="Misc/GunModInfAmmo"}
aW:Toggle{Name="Fire Rate",Flag="Misc/GunModFireRate"}
aW:Slider{Name="Fire Rate Value",Default=0,Min=0,Max=0.1,Flag="Misc/GunModFireRateValue",Interval=0.01}




end

do
local aT=aS[3].Left
local aU=aS[3].Right

local aV=aT:MultiSection{Names={"Enemy","Team"}}
local aW=aU:Section{Name="Esp Settings"}
do
for aX,aY in aV do
local aZ="Enemy"
if aX==1 then

aZ="Enemy"
elseif aX==2 then

aZ="Team"
end
aY:Toggle{Name="Enabled",Default=false,Flag=aZ.."/Enabled"}
local a_=aY:Toggle{Name="Box",Default=false,Flag=aZ.."/Box",Callback=function(a_)
aN.EspChanged:Fire(aZ.."/Box",a_)
end}

a_:Colorpicker{Name="Box Color 1",Color=y(255,0,0),Flag=aZ.."/BoxColor1",Callback=function(a0)
aN.EspChanged:Fire(aZ.."/BoxColor1",a0)
end}
a_:Colorpicker{Name="Box Color 2",Color=y(255,0,0),Flag=aZ.."/BoxColor2",Callback=function(a0)
aN.EspChanged:Fire(aZ.."/BoxColor2",a0)
end}

local a0=aY:Toggle{Name="Box Fill",Default=false,Flag=aZ.."/BoxFill",Callback=function(a0)
aN.EspChanged:Fire(aZ.."/BoxFill",a0)
end}
a0:Colorpicker{Name="Box Fill Color 1",Color=y(255,0,0),Alpha=0.5,Flag=aZ.."/BoxFillColor1",Callback=function(a1)
aN.EspChanged:Fire(aZ.."/BoxFillColor1",a1)
end}
a0:Colorpicker{Name="Box Fill Color 2",Color=y(255,0,0),Alpha=0.5,Flag=aZ.."/BoxFillColor2",Callback=function(a1)
aN.EspChanged:Fire(aZ.."/BoxFillColor2",a1)
end}

aY:Toggle{Name="Image",Default=false,Flag=aZ.."/Image",Callback=function(a1)
aN.EspChanged:Fire(aZ.."/Image",a1)
end}
aY:Dropdown{Name="Image Type",Items={"Rem","Aiko"},Flag=aZ.."/ImageType",Default="Aiko",Callback=function(a1)
aN.EspChanged:Fire(aZ.."/ImageType",a1)
end}
aY:Slider{Name="Image Transparency",Default=0.5,Min=0,Max=1,Flag="Esp/ImageTransparency",Interval=0.1,Callback=function(a1)
aN.EspChanged:Fire("Esp/ImageTransparency",a1)
end}

local a1=aY:Toggle{Name="Name",Default=false,Flag=aZ.."/Name",Callback=function(a1)
aN.EspChanged:Fire(aZ.."/Name",a1)
end}
a1:Colorpicker{Name="Name Color",Default=y(255,255,255),Flag=aZ.."/NameColor",Callback=function(a2)
aN.EspChanged:Fire(aZ.."/NameColor",a2)
end}
local a2=aY:Toggle{Name="Distance",Default=false,Flag=aZ.."/Distance",Callback=function(a2)
aN.EspChanged:Fire(aZ.."/Distance",a2)
end}
a2:Colorpicker{Name="Distance Color",Default=y(255,255,255),Flag=aZ.."/DistanceColor",Callback=function(a3)
aN.EspChanged:Fire(aZ.."/DistanceColor",a3)
end}
local a3=aY:Toggle{Name="Tool",Default=false,Flag=aZ.."/Tool",Callback=function(a3)
aN.EspChanged:Fire(aZ.."/Tool",a3)
end}
a3:Colorpicker{Name="Tool Color",Default=y(255,255,255),Flag=aZ.."/ToolColor",Callback=function(a4)
aN.EspChanged:Fire(aZ.."/ToolColor",a4)
end}
local a4=aY:Toggle{Name="Health Bar",Default=false,Flag=aZ.."/HealthBar",Callback=function(a4)
aN.EspChanged:Fire(aZ.."/HealthBar",a4)
end}
a4:Colorpicker{Name="Health Bar Color 1",Color=y(0,255,0),Alpha=0,Flag=aZ.."/HealthBarColor1",Callback=function(a5)
aN.EspChanged:Fire(aZ.."/HealthBarColor1",a5)
end}
a4:Colorpicker{Name="Health Bar Color 2",Color=y(255,0,0),Alpha=0,Flag=aZ.."/HealthBarColor2",Callback=function(a5)
aN.EspChanged:Fire(aZ.."/HealthBarColor2",a5)
end}
aY:Dropdown{Name="Health Bar Side",Items={"Left","Right","Top","Bottom"},Flag=aZ.."/HealthBarSide",Default="Left",Callback=function(a5)
aN.EspChanged:Fire(aZ.."/HealthBarSide",a5)
end}
aY:Slider{Name="Health Bar Thickness",Default=1,Min=1,Max=2,Flag="Esp/HealthBarThickness",Interval=1,Callback=function(a5)
aN.EspChanged:Fire("Esp/HealthBarThickness",a5)
end}
local a5=aY:Toggle{Name="Health Bar Number",Default=false,Flag=aZ.."/HealthBarNumber",Callback=function(a5)
aN.EspChanged:Fire(aZ.."/HealthBarNumber",a5)
end}
a5:Colorpicker{Name="Health Bar Number Color",Color=y(255,255,255),Alpha=0,Flag=aZ.."/HealthBarNumberColor",Callback=function(a6)
aN.EspChanged:Fire(aZ.."/HealthBarNumberColor",a6)
end}
local a6=aY:Toggle{Name="Chams",Default=false,Flag=aZ.."/Chams",Callback=function(a6)
aN.EspChanged:Fire(aZ.."/Chams",a6)
end}
a6:Colorpicker{Name="Chams Color",Color=y(255,255,255),Flag=aZ.."/ChamsColor",Callback=function(a7)
aN.EspChanged:Fire(aZ.."/ChamsColor",a7)
end}
a6:Colorpicker{Name="Chams Glow Color",Color=y(255,255,255),Flag=aZ.."/ChamsGlowColor",Callback=function(a7)
aN.EspChanged:Fire(aZ.."/ChamsGlowColor",a7)
end}
a6:Slider{Name="Chams Transparency",Default=0.5,Min=0,Max=1,Flag=aZ.."/ChamsTransparency",Interval=0.01,Callback=function(a7)
aN.EspChanged:Fire(aZ.."/ChamsTransparency",a7)
end}

end
end
do
aW:Slider{Name="Max Distance",Default=500,Min=0,Max=1000,Flag="Esp/Distance"}
aW:Toggle{Name="Fade On Distance",Default=false,Flag="Esp/FadeOnDistance"}
aW:Slider{Name="Scale",Default=1,Min=0.01,Max=2,Flag="Esp/Scale",Interval=0.01}
aW:Dropdown{Name="Text Cases",Items={"Normal","UPPER","lower"},Flag="Esp/TextCases",Default="Normal",Callback=function(aX)
aN.EspChanged:Fire("Esp/TextCases",aX)
end}
aW:Dropdown{Name="Text Wrapper",Items={"None","[Brackets]","{Braces}"},Flag="Esp/TextWrapper",Default="None",Callback=function(aX)
aN.EspChanged:Fire("Esp/TextWrapper",aX)
end}
aW:Slider{Name="Health Bar Speed",Default=0.1,Min=0.05,Max=0.9,Flag="Esp/HealthBarSpeed",Interval=0.01}
aW:Slider{Name="Fade Time",Default=0.5,Min=0.1,Max=2,Suffix="s",Flag="Esp/FadeTime",Interval=0.1,Callback=function(aX)
aN.EspChanged:Fire("Esp/FadeTime",aX)
end}
aW:Dropdown{Name="Fade Easing Style",Items=aG.Constants.EasingStyles,Flag="Esp/FadeEasingStyle",Default="Exponential",Callback=function(aX)
aN.EspChanged:Fire("Esp/FadeEasingStyle",aX)
end}
end
end

do
local aT=aS[4].Left
local aU=aS[4].Right

local aV=aT:MultiSection{Names={"Viewmodel","User Interface"}}
local aW=aU:MultiSection{Names={"Camera","World"}}
local aX,aY=M(aV)
local aZ,a_=M(aW)
aX:Toggle{Name="Viewmodel Offset",Flag="Visuals/VmOffset"}
aX:Slider{Name="X",Default=0,Min=-180,Max=180,Flag="Visuals/VmOffsetX",Interval=1,Callback=function(a0)
ay.ViewmodelOffsetX=P(a0)
end}
aX:Slider{Name="Y",Default=0,Min=-180,Max=180,Flag="Visuals/VmOffsetY",Interval=1,Callback=function(a0)
ay.ViewmodelOffsetY=P(a0)
end}
aX:Slider{Name="Z",Default=0,Min=-180,Max=180,Flag="Visuals/VmOffsetZ",Interval=1,Callback=function(a0)
ay.ViewmodelOffsetZ=P(a0)
end}
aX:Slider{Name="Roll",Default=0,Min=-360,Max=360,Flag="Visuals/VmOffsetRoll",Interval=1,Callback=function(a0)
ay.ViewmodelOffsetRoll=P(a0)
end}
aX:Slider{Name="Yaw",Default=0,Min=-360,Max=360,Flag="Visuals/VmOffsetYaw",Interval=1,Callback=function(a0)
ay.ViewmodelOffsetYaw=P(a0)
end}
aX:Slider{Name="Pitch",Default=0,Min=-360,Max=360,Flag="Visuals/VmOffsetPitch",Interval=1,Callback=function(a0)
ay.ViewmodelOffsetPitch=P(a0)
end}

aZ:Toggle{Name="Third Person",Flag="Visuals/ThirdPerson"}:Keybind{Name="Third Person Key",Flag="Visuals/ThirdPersonKey",Mode="toggle"}
aZ:Slider{Name="Third Person Transition Duration",Default=0.2,Min=0.5,Max=2,Flag="Visuals/ThirdPersonDuration",Interval=0.01}
aZ:Slider{Name="Third Person Distance",Default=1,Min=1,Max=50,Flag="Visuals/ThirdPersonDist",Interval=1}
aZ:Slider{Name="Field Of View",Default=80,Min=60,Max=120,Flag="Visuals/CameraFieldOfView",Interval=1,Callback=function(a0)
av.FieldOfView=a0
end}

aY:Toggle{Name="Hitmarker",Flag="Visuals/Hitmarker"}
aY:Dropdown{Name="Hitmarker Type",Items={"2D","3D"},Flag="Visuals/HitmarkerType",Default="2D"}
aY:Slider{Name="Hitmarker Duration",Default=0.2,Min=0,Max=1,Flag="Visuals/HitmarkerDuration",Interval=0.01}
aY:Slider{Name="Hitmarker Fade Time Duration",Default=0.2,Min=0,Max=1,Flag="Visuals/HitmarkerFadeTimeDuration",Interval=0.01,Callback=function(a0)
ay.FadeHitmarker=TweenInfo.new(a0,Enum.EasingStyle.Exponential,Enum.EasingDirection.Out)
end}
local a0=a_:Toggle{Name="Ambience",Flag="Visuals/Ambience",Tooltip="Changes the map's ambient colors to your defined colors."}
a0:Colorpicker{Name="Outside Ambience",Color=y(117,76,236),Flag="Visuals/OutdoorAmbient"}
a0:Colorpicker{Name="Inside Ambience",Color=y(117,76,236),Flag="Visuals/InsideAmbience"}

a_:Toggle{Name="Force Time",Flag="Visuals/ForceTime",Tooltip="Forces the time to the time set by your below."}
a_:Slider{Name="Custom Time",Default=0,Min=0,Max=24,Flag="Visuals/CustomTime",Interval=1,Suffix="h"}



tostring"Fuck you."
end

do
local aT=aS[5].Left local aU=
aS[5].Right

local aV=aJ.Directory.."/lua"

local aW=aT:Section{Name="Luas"}
local aX=aW:List{Name="Lua Scripts",Items=GetFilesName(listfiles(aV)),Flag="Extra/LuaScript"}
aW:ButtonHolder{}
aW:Button{Name="Load Lua Scripts",Callback=function()
if aL["Extra/LuaScript"]==nil then
aJ:Notification{Text="Please select a Lua script to load."}
return
end
local aY,aZ=pcall(loadstring,readfile(aV.."/"..aL["Extra/LuaScript"]))
if not aY then
aJ:Notification{Text="Failed to load Lua script, errors will be displayed in the console."}
warn(aZ)
else
local a_,a0=pcall(aZ)
if not a_ then
aJ:Notification{Text="Lua script errored, errors will be displayed in the console."}
warn(a0)
else
aJ:Notification{Text="Successfully loaded Lua script."}
for a1,a2 in aK.Preset do
pcall(function()
aJ:UpdateTheme(a1,a2)
end)
end
end
end
end}
aW:Button{Name="Reload Lua Scripts",Callback=function()
local aY=pcall(function()
aX.RefreshOptions(GetFilesName(listfiles(aV)))
end)
if not aY then
aJ:Notification{Text="Failed to reload Lua scripts."}
else
aJ:Notification{Text="Successfully reloaded Lua scripts."}
end
end}
end

do
local aT=aG.Visuals.Functions
local aU=aG.Visuals.States local aV=
aG.Constants
aT.Hitmark=function(aW)
if aL["Visuals/Hitmarker"]==false then return false end
local aX=c(aP.Hitmarker.Holder)
aX.Parent=aG.MainScreenGui
aX.Visible=false

if aG.RageBot.Active~=nil and aG.RageBot.Active.Point then
aW=aG.RageBot.Active.Point
end
if aL["Visuals/HitmarkerType"]=="2D"then
for aY,aZ in e(aX)do
aD.SetRenderProperty(aZ,"BackgroundTransparency",0)
if aZ:FindFirstChild"Glow"then
aD.SetRenderProperty(aZ.Glow,"ImageTransparency",0.8)
end
end
af(aL["Visuals/HitmarkerDuration"],function()
local aY
for aZ,a_ in e(aX)do
local a0=ak:Create(a_,ay.FadeHitmarker,{BackgroundTransparency=1})
a0:Play()
if a_:FindFirstChild"Glow"then
local a1=ak:Create(a_.Glow,ay.FadeHitmarker,{ImageTransparency=1})
a1:Play()
aY=a1
end
if not aY then aY=a0 end
end
if aY then
aY.Completed:Wait()
end
aX:Destroy()
end)
return true
elseif aL["Visuals/HitmarkerType"]=="3D"then
aX.Position=v(5000,5000)
local aY

aY=am.RenderStepped:Connect(function()
local aZ,a_=aa(av,aW)
if a_ then
aX.Position=v(aZ.X,aZ.Y)
aX.Visible=true
else
aX.Visible=false
end
end)
for aZ,a_ in e(aX)do
aD.SetRenderProperty(a_,"BackgroundTransparency",0)
if a_:FindFirstChild"Glow"then
aD.SetRenderProperty(a_.Glow,"ImageTransparency",0.8)
end
end
af(aL["Visuals/HitmarkerDuration"],function()
local aZ
for a_,a0 in e(aX)do
local a1=ak:Create(a0,ay.FadeHitmarker,{BackgroundTransparency=1})
a1:Play()
if g(a0,"Glow")then
local a2=ak:Create(a0.Glow,ay.FadeHitmarker,{ImageTransparency=1})
a2:Play()
aZ=a2
end
if not aZ then aZ=a1 end
end
if aZ then
aZ.Completed:Wait()
end
if aY then aY:Disconnect()end
aX:Destroy()
end)

return true
end

return false
end

aT.ResetLighting=function(aW)
local aX=g(al,"Map")
if not aX then return end
local aY=g(aX,"Lighting")

if not aY then return end

if aW=="Ambience"then
if aj.Ambient~=aY.Ambient.Value then
aj.Ambient=aY.Ambient.Value
end
if aj.OutdoorAmbient~=aY.OutdoorAmbient.Value then
aj.OutdoorAmbient=aY.OutdoorAmbient.Value
end
elseif aW=="Time"then
if aj.ClockTime~=aY.ClockTime.Value then
aj.ClockTime=aY.ClockTime.Value
end
elseif aW=="All"then
for aZ,a_ in e(aY)do
if aj[aZ]then
pcall(function()
aj[aZ]=a_
end)
end
end
end

end

aT.Lighting=function()
if aL["Visuals/Ambience"]then
aj.Ambient=aL["Visuals/InsideAmbience"].Color
aj.OutdoorAmbient=aL["Visuals/OutdoorAmbient"].Color
else
aT.ResetLighting"Ambience"
end
if aL["Visuals/ForceTime"]then
aj.ClockTime=aL["Visuals/CustomTime"]or 10
else
aT.ResetLighting"Time"
end
end

aT.ThirdPerson=function(aW)
local aX=aL["Visuals/ThirdPersonDist"]
local aY=aL["Visuals/ThirdPersonDuration"]

if aL["Visuals/ThirdPerson"]and aL["Visuals/ThirdPersonKey"].Active then
do
if aW=="Out"and aU.ThirdPerson~="Out"then
do
if aU.ThirdPerson~="Transitioing_Out"then
do
aU.ThirdPerson="Transitioing_Out"
aU.ThirdPersonStartTime=_()
end
end

local aZ=_()-aU.ThirdPersonStartTime
local a_=O(aZ/aY,0,1)

local a0=a_<0.5 and 2*a_*a_ or 1-V(-2*a_+2,2)/2
local a1=Y(0.5,aX,a0)
ar.CameraMaxZoomDistance=a1
ar.CameraMinZoomDistance=a1

if a_>=1 then
do
aU.ThirdPerson="Out"
end
end
end
elseif aW=="In"and aU.ThirdPerson~="In"then
do
if aU.ThirdPerson~="Transitioing_In"then
do
aU.ThirdPerson="Transitioing_In"
aU.ThirdPersonStartTime=_()
end
end

local aZ=_()-aU.ThirdPersonStartTime
local a_=O(aZ/aY,0,1)

local a0=a_<0.5 and 2*a_*a_ or 1-V(-2*a_+2,2)/2
local a1=Y(aX,0.5,a0)
ar.CameraMaxZoomDistance=a1
ar.CameraMinZoomDistance=a1

if a_>=1 then
do
aU.ThirdPerson="In"
end
end
end
elseif aU.ThirdPerson=="Out"then
do
ar.CameraMaxZoomDistance=aX
ar.CameraMinZoomDistance=aX
end
end
end
else
do
ar.CameraMaxZoomDistance=0.5
ar.CameraMinZoomDistance=0.5
aU.ThirdPerson="In"
end
end
end
end

do
aG.Esp.GetBoundingBoxes=function(aT,aU,aV,aW,aX)
local aY,aZ=X,-X
local a_,a0=X,-X

if aW and aX and aX.LastCharacter then
local a1=aX.LastCharacter
local a2,a3,a4,a5=X,X,-X,-X

local a6,a7=a1:GetBoundingBox()

local a8=a7.X*0.5
local a9=a7.Y*0.5
local ba=a7.Z*0.5

local bb,bc,bd,be,
bf,bg,bh,bi,
bj,bk,bl,bm=r(a6)

local bn={a8,-a8,a8,-a8,a8,-a8,a8,-a8}
local bo={a9,a9,-a9,-a9,a9,a9,-a9,-a9}
local bp={ba,ba,ba,ba,-ba,-ba,-ba,-ba}

local bq,br
for bs=1,8 do
local bt,bu,bv=bn[bs],bo[bs],bp[bs]
local bw=bb*bt+bc*bu+bd*bv+be
local bx=bf*bt+bg*bu+bh*bv+bi
local by=bj*bt+bk*bu+bl*bv+bm
bq,br=aa(av,s(bw,bx,by))
if br then
if bq.X<a2 then a2=bq.X end
if bq.X>a4 then a4=bq.X end
if bq.Y<a3 then a3=bq.Y end
if bq.Y>a5 then a5=bq.Y end
end
end

if a2==X then
a2=aU.X-20
a4=aU.X+20
a3=aU.Y-40
a5=aU.Y+40
end

return
Q(a2),
Q(a3),
Q(a4),
Q(a5),
Q(a2+(a4-a2)/2),
Q(a3+(a5-a3)/2)
else
local a1=2.68*aV local a2=
1.6*aV

local a3=aa(av,aT.Position+s(0,a1,0))
local a4=a3.Y-aU.Y

local a5=a4/1.5
local a6=aU.X
local a7=aU.Y

local a8=a6+a5
local a9=a6-a5
local ba=a7+(a5*1.15)
local bb=a7-(a4*1.15)

local bc={
t(a8,ba),
t(a9,bb),
t(a8,bb),
t(a9,ba),
}

for bd,be in bc do
if aY>be.X then aY=be.X end
if aZ<be.X then aZ=be.X end
if a_>be.Y then a_=be.Y end
if a0<be.Y then a0=be.Y end
end

return
Q(aY),
Q(a_),
Q(aZ),
Q(a0),
Q(aY+(aZ-aY)/2),
Q(a_+(a0-a_)/2)
end
end

aG.Esp.Hide=function(aT)
if aT.IsFading then return end
local aU=aT.Objects.FrameHolder
if aU and aD.GetRenderProperty(aU,"Visible")==true then
aD.SetRenderProperty(aU,"Visible",false)
end
end
aG.Esp.Show=function(aT)
if aT.IsFading then return end
local aU=aT.Objects.FrameHolder
if aU and aD.GetRenderProperty(aU,"Visible")==false then
aD.SetRenderProperty(aU,"Visible",true)
end
end

aG.Esp.ApplyTextLabel=function(aT)
local aU=aL["Esp/TextCases"]
local aV=aL["Esp/TextWrapper"]

if not aG.Esp.SettingsCache.TextCases[aT]then
local aW=aT.Text
aG.Esp.SettingsCache.TextCases[aT]={
Upper=F(aW),
Normal=aW,
Lower=G(aW)
}
end

local aW=aG.Esp.SettingsCache.TextCases[aT]

local aX
if aU=="UPPER"then
aX=aW.Upper
elseif aU=="lower"then
aX=aW.Lower
else
aX=aW.Normal
end

if aV=="[Brackets]"then
aT.Text="["..aX.."]"
elseif aV=="{Braces}"then
aT.Text="{"..aX.."}"
else
aT.Text=aX
end

aG.Esp.FixTextPadding(aT)
end
aG.Esp.UpdateElement=function(aT)
local aU=aG.Esp.Entities[aT]
if not aU then return end
local aV=aU.Objects

local aW=aG.Utility.GetTeam(aT)
local aX=aG.Utility.GetTeam(ar)
local aY=aW==aX
local aZ=aY==true and"Team"or"Enemy"local a_=

{Left=
aV.SideLeft,Right=
aV.SideRight,Top=
aV.SideTop,Bottom=
aV.SideBottom,
}

do
aG.Esp.SettingsCache.TweenInformation[1]=TweenInfo.new(aL["Esp/FadeTime"],Enum.EasingStyle[aL["Esp/FadeEasingStyle"] ],Enum.EasingDirection.Out)
end

do
aD.SetRenderProperty(aV.HealthBarNumber,"Visible",aL[aZ.."/HealthBarNumber"]and aL[aZ.."/HealthBar"])
if aD.Fonts[Font]then
local a0=Font=="SmallestPixel7"and 9 or 12
aD.SetRenderProperty(aV.HealthBarNumber,"Font",aD.Fonts[Font])
aD.SetRenderProperty(aV.HealthBarNumber,"TextSize",a0)
end
aV.HealthBarNumber.TextColor3=aL[aZ.."/HealthBarNumberColor"].Color
end

do
local a0=aL[aZ.."/Image"]
local a1=aL[aZ.."/ImageType"]or"Aiko"
local a2=aL["Esp/ImageTransparency"]or 0
local a3=aV.Image
aD.SetRenderProperty(a3,"Visible",a0)
aD.SetRenderProperty(a3,"ImageTransparency",a2)
local a4=aG.Assets.Images.Girls[a1]
if a4 then
aD.SetRenderProperty(a3,"Image",a4)
end
end


do
local a0=aL[aZ.."/BoxColor1"].Color or y(255,255,255)
local a1=aL[aZ.."/BoxColor2"].Color or y(255,255,255)

aD.SetRenderProperty(
aV.BoxGradient,
"Color",
z{
A(0,a0),
A(1,a1)
}
)

aD.SetRenderProperty(aV.Box,"Visible",aL[aZ.."/Box"])
aD.SetRenderProperty(aV.FullBoxHolder,"Visible",aL[aZ.."/Box"])
do
local a2=aL[aZ.."/BoxFillColor1"].Color or y(255,255,255)
local a3=aL[aZ.."/BoxFillColor2"].Color or y(255,255,255)
local a4=aL[aZ.."/BoxFillColor1"].Transparency or 0.5
local a5=aL[aZ.."/BoxFillColor2"].Transparency or 0.5

aD.SetRenderProperty(
aV.BoxFillGradient,
"Color",
z{
A(0,a2),
A(1,a3)
}
)

aD.SetRenderProperty(
aV.BoxFillGradient,
"Transparency",
B{
C(0,a4),
C(1,a5)
}
)

aD.SetRenderProperty(aV.BoxFill,"BackgroundTransparency",0)
aD.SetRenderProperty(aV.BoxFill,"Visible",aL[aZ.."/BoxFill"]and aL[aZ.."/Box"])
end


end

do
local a0=aV.Name
a0.Visible=aL[aZ.."/Name"]
a0.TextColor3=aL[aZ.."/NameColor"].Color
aG.Esp.ApplyTextLabel(a0)
end

do
local a0=aV.Distance
a0.Visible=aL[aZ.."/Distance"]
a0.TextColor3=aL[aZ.."/DistanceColor"].Color
aG.Esp.ApplyTextLabel(a0)
end

do
local a0=aV.Tool
a0.Visible=aL[aZ.."/Tool"]
a0.TextColor3=aL[aZ.."/ToolColor"]and aL[aZ.."/ToolColor"].Color or y(255,255,255)
aG.Esp.ApplyTextLabel(a0)
end

do
local a0=aL["Esp/HealthBarThickness"]or 1
aD.SetRenderProperty(aV.HealthBarHolder,"Size",u(0,a0,1,2))
local a1=aL[aZ.."/HealthBarColor1"].Color or y(255,255,255)
local a2=aL[aZ.."/HealthBarColor2"].Color or y(255,255,255)
aU.LastHealthBarSide=nil
aD.SetRenderProperty(
aV.HealthBarFillGradient,
"Color",
z{
A(0,a1),
A(0.5,a1:Lerp(a2,0.5)),
A(1,a2)
}
)
end

do
local a0=aL[aZ.."/Chams"]
if a0 then
if not aU.Chams or not next(aU.Chams)then
aG.Esp.DrawChams(aT,aU)
else local a1=
aL[aZ.."/ChamsColor"]and aL[aZ.."/ChamsColor"].Color or y(255,255,255)
local a2=aL[aZ.."/ChamsGlowColor"]and aL[aZ.."/ChamsGlowColor"].Color or y(255,255,255)
local a3=aL[aZ.."/ChamsTransparency"]or 0.5
local a4=y(a2.R*1275,a2.G*1275,a2.B*1275)
for a5,a6 in aU.Chams do
pcall(function()
a6.Color3=a4
a6.Transparency=a3
end)
end
end
else
aG.Esp.RemoveChams(aU)
end
end


end

aG.Esp.CanChangeTransparency=function(aT,aU)
if aU==nil or aT==nil then return false end
local aV=aT
local aW=true
for aX,aY in aV.NoFade do
if aY==aU then
aW=false
break
end
end
return aW
end
aG.Esp.Fade=function(aT,aU)
local aV=aU
local aW=aT and 0 or 1

for aX,aY in aV.Objects do
if aG.Esp.CanChangeTransparency(aV,aY)==true then
local aZ=aG.Utility.GetTransparency(aY)
if aZ then
local a_=ak:Create(
aY,
aG.Esp.SettingsCache.TweenInformation[1],
{[aZ]=aW}
)
a_:Play()
end
end
end

if aV.Chams then
for aX,aY in aV.Chams do
if H(aX,"main_")then
pcall(function()aY.Transparency=aT and aV.ChamsTransparencyTo or 1 end)
end
end
end
end
aG.Esp.SetTransparency=function(aT,aU)
if aT.LastAlpha==aU then return end
aT.LastAlpha=aU
for aV,aW in aT.Objects do
if aG.Esp.CanChangeTransparency(aT,aW)then
local aX=aG.Utility.GetTransparency(aW)
if aX then
aW[aX]=aU
end
end
end
if aT.Chams then
for aV,aW in aT.Chams do
if H(aV,"main_")then
pcall(function()aW.Transparency=aU end)
end
end
end
end
aG.Esp.FixTextPadding=function(aT)
local aU=aT.FontFace
local aV=""
local aW=false
for aX,aY in az do
if aY==aU then
aV=aX
end
end

if aG.Esp.TextOffsets[aV]then
local aX=aG.Esp.TextOffsets[aV]
local aY=aT.Parent.Name

do
local aZ,a_=aG.Utility.GetTextBounds(
aT.Text,
aT.FontFace,
aT.TextSize
)

if aX.Side[aY]then
local a0=aX.Side[aT.Parent.Name]
aT.Size=v(aZ+a0.X,a_+a0.Y)
else
aT.Size=v(aZ+aX.X,a_+aX.Y)
end

end
aW=true
else
local aX,aY=aG.Utility.GetTextBounds(
aT.Text,
aT.FontFace,
aT.TextSize
)
aT.Size=v(aX,aY)
end

return aW
end
aG.Esp.GetHealth=function(aT)
local aU=i(aT,"Humanoid")

if game.PlaceId==79393329652220 then
local aV=l(aq,aT)
if not aV then return 0,100 end
local aW=j(aV,"Health")
local aX=j(aV,"MaxHealth")
if not aW or not aX then return 0,100 end
return aW,aX
end

if not aU then return 0,100 end
return aU.Health,aU.MaxHealth
end
aG.Esp.GetEquipped=function(aT)
if aT==nil then return end
local aU=g(aT,"EquippedTool")
if not aU then return"None"end
if aU.Value then
return aU.Value
end
return"NOne"
end


aG.Esp.DoNothing=function()
local aT=true
local aU=true
local aV="Yuri"
local aW="Dexsai"
if aT==true and aU==true then
local aX={aV,aW}
return aX
end
return"sorry dexsai"
end

aG.Esp.RemoveChams=function(aT)
if not aT.Chams then return end
for aU,aV in aT.Chams do
pcall(function()aV:Destroy()end)
aT.Objects["Chams_main_"..aU]=nil
aT.NoFade["Chams_glow_"..aU]=nil
end
aT.Chams={}
end
aG.Esp.DrawChams=function(aT,aU)
aG.Esp.RemoveChams(aU)

local aV=aG.Utility.GetTeam(aT)
local aW=aG.Utility.GetTeam(ar)
local aX=(aV==aW)and"Team"or"Enemy"

if not aL[aX.."/Chams"]then return end

local aY=aT.Character or aU.LastCharacter
if not aY then return end

local aZ=aL[aX.."/ChamsGlowColor"]and aL[aX.."/ChamsGlowColor"].Color or y(255,255,255)
local a_=aL[aX.."/ChamsColor"]and aL[aX.."/ChamsColor"].Color or y(255,255,255)
local a0=aL[aX.."/ChamsTransparency"]or 0.5
aU.ChamsTransparencyTo=a0
local a1=y(aZ.R*1275,aZ.G*1275,aZ.B*1275)

aU.Chams={}

local a2=0
for a3,a4 in e(aY)do
if not ah(a4,"BasePart")then continue end
local a5=a4
if a5.Transparency>=1 then continue end

local a6=a5.Name=="Head"or a5.Name=="FakeHead"
local a7=a6 and"Cylinder"or"Box"

local function MakeAdorn(a8,a9,ba)
local bb
if a7=="Cylinder"then
bb=a"CylinderHandleAdornment"
bb.Height=a5.Size.Y+0.04
bb.Radius=(a5.Size.X*0.5)+0.02
bb.CFrame=o(s(),s(0,1,0))
else
bb=a"BoxHandleAdornment"
bb.Size=a5.Size+s(0.04,0.04,0.04)
end
bb.Name="Chams"
bb.AlwaysOnTop=true
bb.ZIndex=ba
bb.Adornee=a5
bb.Color3=a8
bb.Transparency=a9
pcall(function()bb.Shading=Enum.AdornShading.XRayShaded end)
bb.Parent=a5
return bb
end

local a8=MakeAdorn(a1,-1,a6 and 9 or 8)
local a9=MakeAdorn(a_,a0,a6 and 10 or 9)

a2=a2+1
aU.Chams["glow_"..a2]=a8
aU.Chams["main_"..a2]=a9

aU.NoFade["Chams_glow_"..a2]=a8
aU.Objects["Chams_main_"..a2]=a9
end
end

aG.Esp.AddEntity=function(aT)
local aU={}
local aV={}

local aW={Objects=aU,NoFade=aV,IsOnScreen=false,IsFading=false,HasFadedIn=false,LastTool=nil,LastToolText=nil}
aG.Esp.Entities[aT]=aW

aU.FrameHolder=aD.new("Frame",{Visible=false,Parent=aG.Esp.Holder,BackgroundTransparency=1})
aU.Box=aD.new("Frame",{Visible=true,Parent=aU.FrameHolder,Size=u(1,0,1,0),BackgroundTransparency=1})
aV.Holder=aU.FrameHolder
aV.BoxHolder=aU.Box

aU.FullBoxHolder=aD.new("Frame",{Visible=false,Parent=aU.Box,Size=u(1,0,1,0),BackgroundTransparency=1})
aV.FullBoxHolder=aU.FullBoxHolder
aU.BoxStroke=aD.new("UIStroke",{Parent=aU.FullBoxHolder,LineJoinMode="Miter",Thickness=1,ZIndex=5,Color=y(255,255,255)})
aU.BoxOutline=aD.new("UIStroke",{Parent=aU.FullBoxHolder,Thickness=3,Color=y(0,0,0),BorderOffset=w(0,-1),LineJoinMode="Miter"})
aU.BoxGradient=aD.new("UIGradient",{Parent=aU.BoxStroke,Rotation=90,Color=ColorSequence.new{
ColorSequenceKeypoint.new(0,y(255,255,255)),
ColorSequenceKeypoint.new(1,y(255,255,255))
}})

aU.SideLeft=aD.new("Frame",{Visible=true,Parent=aU.FrameHolder,Size=u(1,0,1,0),Position=u(-1,-0,0,-4),BackgroundTransparency=1,Name="Left"})
aU.SideRight=aD.new("Frame",{Visible=true,Parent=aU.FrameHolder,Size=u(1,0,1,0),Position=u(1,0,0,-4),BackgroundTransparency=1,Name="Right"})
aU.SideBottom=aD.new("Frame",{Visible=true,Parent=aU.FrameHolder,Size=u(1,0,1,0),Position=u(0,0,1,0),BackgroundTransparency=1,Name="Bottom"})
aU.SideTop=aD.new("Frame",{Visible=true,Parent=aU.FrameHolder,Size=u(1,0,1,0),Position=u(0,0,-1,-0),BackgroundTransparency=1,Name="Top"})
aV.Left=aU.SideLeft
aV.Right=aU.SideRight
aV.Bottom=aU.SideBottom
aV.Top=aU.SideTop
aD.new("UIListLayout",{Parent=aU.SideLeft,HorizontalAlignment="Right",Padding=w(0,1)})
aD.new("UIListLayout",{Parent=aU.SideRight,HorizontalAlignment="Left",Padding=w(0,1)})
aD.new("UIListLayout",{Parent=aU.SideBottom,HorizontalAlignment="Center",VerticalAlignment="Top",Padding=w(0,1)})
aD.new("UIListLayout",{Parent=aU.SideTop,HorizontalAlignment="Center",Padding=w(0,1),VerticalAlignment="Bottom"})

aD.new("UIPadding",{
PaddingTop=UDim.new(0,0),
PaddingBottom=UDim.new(0,0),
Parent=aU.SideLeft,
PaddingRight=UDim.new(0,4),
PaddingLeft=UDim.new(0,0),
})
aD.new("UIPadding",{
PaddingTop=UDim.new(0,0),
PaddingBottom=UDim.new(0,0),
Parent=aU.SideRight,
PaddingRight=UDim.new(0,0),
PaddingLeft=UDim.new(0,4),
})
aD.new("UIPadding",{
PaddingTop=UDim.new(0,2),
PaddingBottom=UDim.new(0,0),
Parent=aU.SideBottom,
PaddingRight=UDim.new(0,0),
PaddingLeft=UDim.new(0,0),
})
aD.new("UIPadding",{
PaddingTop=UDim.new(0,0),
PaddingBottom=UDim.new(0,3),
Parent=aU.SideTop,
PaddingRight=UDim.new(0,0),
PaddingLeft=UDim.new(0,0),
})












aU.Name=aD.new("TextLabel",{
Text=aT.Name,
Font=4,
TextSize=9,
Parent=aU.SideTop
})
aU.NameOutline=aD.new("UIStroke",{Parent=aU.Name,Thickness=1,Color=y(0,0,0),LineJoinMode="Miter"})
aG.Esp.FixTextPadding(aU.Name)

aU.Distance=aD.new("TextLabel",{
Text="0m",
Font=4,
TextSize=9,
Parent=aU.SideBottom
})
aU.DistanceOutline=aD.new("UIStroke",{Parent=aU.Distance,Thickness=1,Color=y(0,0,0),LineJoinMode="Miter"})
aG.Esp.FixTextPadding(aU.Distance)

aU.Tool=aD.new("TextLabel",{
Text="None",
Font=4,
TextSize=9,
Parent=aU.SideBottom
})
aU.ToolOutline=aD.new("UIStroke",{Parent=aU.Tool,Thickness=1,Color=y(0,0,0),LineJoinMode="Miter"})
aG.Esp.FixTextPadding(aU.Tool)

aU.HealthBarHolder=aD.new("Frame",{
Visible=true,
Parent=aU.FrameHolder,
BackgroundColor3=y(0,0,0),
BackgroundTransparency=0,
Size=u(0,1,1,2),
AnchorPoint=t(1,0),
Position=u(0,-4,0,-1),
BorderSizePixel=0,
ZIndex=4,
ClipsDescendants=true
})
aU.HealthBarFill=aD.new("Frame",{
Parent=aU.HealthBarHolder,
BackgroundColor3=y(255,255,255),
Size=u(1,0,1,0),
AnchorPoint=t(0,1),
Position=u(0,0,1,0),
BorderSizePixel=0,
ZIndex=5
})
aU.HealthBarOutline=aD.new("UIStroke",{
Parent=aU.HealthBarHolder,
Thickness=1,
Color=y(0,0,0),
LineJoinMode="Miter"
})

aU.HealthBarNumber=aD.new("TextLabel",{
Text="100",
Font=4,
TextSize=9,
Parent=aU.FrameHolder,
TextColor3=y(255,255,255),
BackgroundTransparency=1,
ZIndex=7,
AnchorPoint=t(0.5,1),
Position=u(0,0,0,0),
Size=v(30,12),
ClipsDescendants=false,
})
aU.HealthBarNumberOutline=aD.new("UIStroke",{
Parent=aU.HealthBarNumber,
Thickness=1,
Color=y(0,0,0),
LineJoinMode="Miter"
})

aU.HealthBarFillGradient=aD.new("UIGradient",{Parent=aU.HealthBarFill,Rotation=90,Color=ColorSequence.new{
ColorSequenceKeypoint.new(0,y(0,255,0)),
ColorSequenceKeypoint.new(1,y(255,0,0))
}})

aU.BoxFill=aD.new("Frame",{Visible=false,Parent=aU.Box,Size=u(1,0,1,0),BackgroundTransparency=0.5,ZIndex=-5})
aU.BoxFillGradient=aD.new("UIGradient",{Parent=aU.BoxFill,Rotation=90,Color=ColorSequence.new{
ColorSequenceKeypoint.new(0,y(255,255,255)),
ColorSequenceKeypoint.new(1,y(0,0,0))
}})
aU.Image=aD.new("ImageLabel",{
Visible=true,
Parent=aU.FrameHolder,
Size=u(1,0,1,0),
Position=u(0.5,0,0.5,0),
AnchorPoint=t(0.5,0.5),
BackgroundTransparency=1,
ZIndex=-3,
Image=aG.Assets.Images.Girls.Aiko
})

aW.Render=function()
local aX=aT.Character
if not aX then
if not aW.IsFading then
aG.Esp.Hide(aW)return
end
end

if aX then
local aY=g(aX,"HumanoidRootPart")
local aZ=g(aX,"Head")
local a_=i(aX,"Humanoid")
if aY then
aW.LastCFrame=aY.CFrame
aW.LastRootSize=aY.Size
aW.LastCharacter=aX
end
if aZ then
aW.LastHeadCFrame=aZ.CFrame
aW.LastHeadSize=aZ.Size
end
if a_ then
aW.LastHipHeight=a_.HipHeight
end
end

if not aW.LastCFrame then aG.Esp.Hide(aW)return end
local aY=aW.LastCFrame

local aZ=aY.Position
local a_,a0=aa(av,aZ)

if aW.IsFading then
if a0 then local a1=
Q(a_.X)-1 local a2=
Q(a_.Y)-1
local a3,a4,a5,a6=aG.Esp.GetBoundingBoxes(aY,a_,aL["Esp/Scale"],false,aW)
local a7=(a5+1)-(a3-1)
local a8=(a6+1)-(a4-1)
aD.SetRenderProperty(aU.FrameHolder,"Position",v(a3-1,a4-1))
aD.SetRenderProperty(aU.FrameHolder,"Size",v(a7,a8))
else
aD.SetRenderProperty(aU.FrameHolder,"Visible",false)
end
return
end

local a2=aG.Utility.GetTeam(aT)
if a2~=aW.LastTeam then
aG.Esp.UpdateElement(aT)
end
aW.LastTeam=a2
local a3=aG.Utility.GetTeam(ar)
local a4=a2==a3
local a5=a4==true and"Team"or"Enemy"

local a6=aL["Esp/TextCases"]
local a7=aL["Esp/TextWrapper"]

if not aL[a5 .."/Enabled"]then aG.Esp.Hide(aW)return end

local a8=aL["Esp/Distance"]or 500
local a9=(av.CFrame.Position-aZ).Magnitude

if a9>a8 then
aG.Esp.Hide(aW)
return
end

do
local ba,bb=0,100
if aX then
ba,bb=aG.Esp.GetHealth(aX)
end
local bc=O(ba/R(bb,1),0,1)

aW.HealthRatio=Y(aW.HealthRatio or bc,bc,aL["Esp/HealthBarSpeed"]or 0.1)
local bd=aW.HealthRatio

if bd<=0.01 then
if aD.GetRenderProperty(aU.FrameHolder,"Visible")then
aW.IsFading=true
aW.HasFadedIn=false
aG.Esp.Fade(false,aW)
af(1.1,function()
aW.IsFading=false
aW.LastCFrame=nil
aW.LastCharacter=nil
aW.HealthRatio=nil
aW.LastAlpha=nil
aW.LastTool=nil
aW.LastToolText=nil
aW.LastHealthBarSide=nil
aG.Esp.Hide(aW)
for be,bf in aU do
if aG.Esp.CanChangeTransparency(aW,bf)then
local bg=aG.Utility.GetTransparency(bf)
if bg then
bf[bg]=0
end
end
end
end)
end
return
end

if bc==1 and not aW.HasFadedIn then
aW.HasFadedIn=true
aW.LastAlpha=nil
for be,bf in aU do
if aG.Esp.CanChangeTransparency(aW,bf)then
local bg=aG.Utility.GetTransparency(bf)
if bg then
bf[bg]=1
end
end
end
aG.Esp.Show(aW)
aG.Esp.Fade(true,aW)
else
aG.Esp.Show(aW)
end
end

do
local ba=aU.Distance
if ba.Visible then
local bb=Q(a9).."m"
if a7=="[Brackets]"then
bb="["..bb.."]"
elseif a7=="{Braces}"then
bb="{"..bb.."}"
end
if a6=="UPPER"then
bb=F(bb)
elseif a6=="lower"then
bb=G(bb)
end
if ba.Text~=bb then
ba.Text=bb
aG.Esp.FixTextPadding(ba)
end
end

local bb=aU.Tool
if bb.Visible and aX then
local bc=aG.Esp.GetEquipped(aX)
local bd=bc or"None"
if aW.LastTool~=bd then
aW.LastTool=bd
local be=bd
if a7=="[Brackets]"then
be="["..be.."]"
elseif a7=="{Braces}"then
be="{"..be.."}"
end
if a6=="UPPER"then
be=F(be)
elseif a6=="lower"then
be=G(be)
end
if bb.Text~=be then
bb.Text=be
aG.Esp.FixTextPadding(bb)
end
end
end

if aL["Esp/FadeOnDistance"]then
local bc=a8*0.6
local bd=O((a9-bc)/(a8-bc),0,1)
aG.Esp.SetTransparency(aW,bd)
else
aG.Esp.SetTransparency(aW,0)
end
end local

ba, bb, bc, bd=aG.Esp.GetBoundingBoxes(aY,a_,aL["Esp/Scale"],false,aW)

if a0 then
local be=ba-1
local bf=bb-1
local bg=(bc+1)-be
local bh=(bd+1)-bf

aW.IsOnScreen=true
aD.SetRenderProperty(aU.FrameHolder,"Position",v(be,bf))
aD.SetRenderProperty(aU.FrameHolder,"Size",v(bg,bh))
else
aW.IsOnScreen=false
aG.Esp.Hide(aW)
return
end

do
local be=aL[a5 .."/HealthBar"]
aD.SetRenderProperty(aU.HealthBarHolder,"Visible",be)

local bf="Left"
local bg=aL["Esp/HealthBarThickness"]or 1
local bh=4 local bi=
be and(bg+bh-1)or 0

if be then
local bj=aW.HealthRatio or 1
local bk=aW.LastHealthBarSide~=bf
aW.LastHealthBarSide=bf

if bk then
if bf then
aD.SetRenderProperty(aU.HealthBarHolder,"AnchorPoint",t(1,0))
aD.SetRenderProperty(aU.HealthBarHolder,"Size",u(0,bg,1,2))
aD.SetRenderProperty(aU.HealthBarHolder,"Position",u(0,-bh,0,-1))
end

if bf=="Left"or bf=="Right"then
aD.SetRenderProperty(aU.HealthBarFill,"AnchorPoint",t(0,1))
aD.SetRenderProperty(aU.HealthBarFill,"Position",u(0,0,1,0))
aD.SetRenderProperty(aU.HealthBarFillGradient,"Rotation",90)
else
aD.SetRenderProperty(aU.HealthBarFill,"AnchorPoint",t(0,0))
aD.SetRenderProperty(aU.HealthBarFill,"Position",u(0,0,0,0))
aD.SetRenderProperty(aU.HealthBarFillGradient,"Rotation",0)
end
end

if bf=="Left"or bf=="Right"then
aD.SetRenderProperty(aU.HealthBarFill,"Size",u(1,0,bj,0))
else
aD.SetRenderProperty(aU.HealthBarFill,"Size",u(bj,0,1,0))
end


do
local bl=aU.HealthBarNumber
local bm=aL[a5 .."/HealthBarNumber"]
aD.SetRenderProperty(bl,"Visible",bm and be)
if bm then
local bn=O(W(bj*100),0,100)
local bo=bn
if bl.Text~=bo then
bl.Text=bo
end

local bp="SmallestPixel7"


local bq=0
local br=0
if bp=="SmallestPixel7"then
bq=5-(aL["Esp/HealthBarThickness"]-1)
end


if bf then
aD.SetRenderProperty(bl,"AnchorPoint",t(1,0.5))
aD.SetRenderProperty(bl,"Position",u(0,-(bh)+bq,1-bj,br))
end
end
end
end
end
end
aW.CharacterConn=aT.CharacterAdded:Connect(function()
af(0.5,function()
aW.Chams={}
aG.Esp.UpdateElement(aT)
aG.Esp.DrawChams(aT,aW)
end)
end)
aG.Esp.UpdateElement(aT)
end

aG.Esp.RemoveEntity=function(aT)
local aU=aG.Esp.Entities[aT]
if aU then
if aU.Objects then
for aV,aW in aU.Objects do
aD.DestroyRenderObject(aW)
end
end
aG.Esp.RemoveChams(aU)
if aU.CharacterConn then
aU.CharacterConn:Disconnect()
aU.CharacterConn=nil
end
aG.Esp.Entities[aT]=nil
end
end
aJ:Connection(am.RenderStepped,function(aT)
for aU,aV in aG.Esp.Entities do
if aU and aV and aV.Render then
aV.Render()
end
end
end)
for aT,aU in k(aq)do
aG.Esp.AddEntity(aU)
end
aJ:Connection(aq.PlayerAdded,function(aT)
aG.Esp.AddEntity(aT)
aT.CharacterAdded:Connect(function()
aG.Esp.UpdateElement(aT)
end)
end)
aJ:Connection(aq.PlayerRemoving,function(aT)
aG.Esp.RemoveEntity(aT)
end)
aN.EspChanged:Connect(function(aT,aU)
for aV,aW in k(aq)do
local aX=aG.Esp.Entities[aW]
if aX then
aG.Esp.UpdateElement(aW)
aG.Esp.RemoveChams(aX)
aG.Esp.DrawChams(aW,aX)
end
end
end)
end

do
local aT=aG.Misc.Functions
local aU=aG.Constants
local aV=aG.GarbageCollector
local aW=aG.ClientScript

aT.Movement=function()
local aX=ar.Character
if not aX then return end
local aY=g(aX,"HumanoidRootPart")
local aZ=i(aX,"Humanoid")
if not aY or not aZ then return end

if m(ao,"Space")and aL["Misc/AutoJump"]then
aZ.Jump=true
end

if aL["Misc/Speed"]then
local a_=aL["Misc/SpeedValue"]or 30
local a0=av.CFrame
local a2=s(a0.LookVector.X,0,a0.LookVector.Z).Unit
local a3=s(a0.RightVector.X,0,a0.RightVector.Z).Unit

a_=(aL["Misc/OverrideSpeed"]==true and aL["Misc/OverrideSpeedKey"].Active==true)and aL["Misc/OverrideSpeedValue"]or a_

local a4=s()
if m(ao,"W")then a4=a4+a2 end
if m(ao,"S")then a4=a4-a2 end
if m(ao,"A")then a4=a4-a3 end
if m(ao,"D")then a4=a4+a3 end

local a5=aY.AssemblyLinearVelocity
if a4.Magnitude>0 then
aY.AssemblyLinearVelocity=s(
a4.Unit.X*a_,
a5.Y,
a4.Unit.Z*a_
)
else
aY.AssemblyLinearVelocity=s(
a5.X*0.75,
a5.Y,
a5.Z*0.75
)
end
end
end

aT.HitSound=function(aX)
if aX=="Head"or aX=="HeadHB"then
if not aL["Misc/HeadHitSound"]then return end
local aY=aD.new("Sound",{
SoundId="rbxassetid://"..aU.Sounds[aL["Misc/HeadHitSoundType"] ],
Parent=av,
Volume=aL["Misc/HeadHitSoundVolume"],
PlayOnRemove=true
})
aD.DestroyRenderObject(aY)
else
if not aU.Hitboxes[aX]then return end
if not aL["Misc/HitSound"]then return end
local aY=aD.new("Sound",{
SoundId="rbxassetid://"..aU.Sounds[aL["Misc/HitSoundType"] ],
Parent=av,
Volume=aL["Misc/HitSoundVolume"],
PlayOnRemove=true
})
aD.DestroyRenderObject(aY)
end
end
aT.KillSound=function()
if not aL["Misc/KillSound"]then return end
local aX=aD.new("Sound",{
SoundId="rbxassetid://"..aU.Sounds[aL["Misc/KillSoundType"] ],
Parent=av,
Volume=aL["Misc/KillSoundVolume"],
PlayOnRemove=true
})
aD.DestroyRenderObject(aX)
end
aT.ApplyGunModification=function()
local aX=aW.fgun
local aY=aG.Utility.GetWeaponReference(g(aF.Guns,aX.Name))
if aX=="none"then return end

if aL["Misc/GunMod"]then

if aL["Misc/GunModInfAmmo"]then
aV.StatusTable.ammocount=X
aV.StatusTable.ammocount2=X
end



if aL["Misc/GunModFireRate"]then
aX.FireRate.Value=aL["Misc/GunModFireRateValue"]
else
if aY then
aX.FireRate.Value=aY.FireRate.Value
end
end

else
if aY then
aX.FireRate.Value=aY.FireRate.Value
end
end
end
end

do

local aT=aG.RageBot
local aU=aT.TimeOffset
local aV=aT.TimeOffset2
local aW=aT.Functions

local aX=aG.Constants.MaterialMultipliers
local aY=aG.Constants.RayIgnore
local aZ=aG.Constants.Status
local a_=aG.ClientScript
local a0=aE.ToUse.HitPart
local a2=aZ.Timer
aW.HitPart=function(a3,a4,a5,a6)
local a7=g(ar.Character,"Gun")
local a8=g(a3.Character,a4 or"Head")
local a9=(aG.Utility.IsJumpingOrFalling()or false)
local ba=aG.Utility.EncodePosition(a8.Position)

a0:FireServer(
a8,
ba,
a5,
0,
a7,
nil,
a6 or 1,
0,
true,
av.CFrame.Position,
ag(al),
at,
false,
false,
false,
a9,
true,
aG.Utility.GetNilsForRemote"HitPart"
)
end

aW.GetEnemies=function()
local a3=ay.RageBotCache
local a4=Z()
if a4-a3.LastEnemyUpdate<0.1 then
return a3.Enemies
end
a3.LastEnemyUpdate=a4

local a5=a3.Enemies
J(a5)
local a6=aG.Utility.GetTeam(ar)
local a7=a3.Entities

for a8,a9 in k(aq)do
if a9==ar then continue end


local ba=g(a9,"Status")
if not ba or ba.Alive.Value~=true then
a7[a9]=nil
continue
end

local bb=aG.Utility.GetTeam(a9)
if bb~=a6 then
I(a5,a9)

if not a7[a9]or a7[a9].Character~=a9.Character or not a7[a9].Root then
local bc=a9.Character
if bc then
local bd=g(bc,"Head")
local be=g(bc,"HumanoidRootPart")

if bd and be then
a7[a9]={
Character=bc,
Head=bd,
Root=be
}
else
a7[a9]=nil
end
end
end
end
end

return a5
end
aW.FakeShoot=function()
local a3=g(av,"Arms")
local a4=a_.fgun
if not a3 or a4=="none"then return end

local a5=g(a3,"fire")
if not a5 then return end

local a6=i(a3,"AnimationController")
if a6 then
a6:LoadAnimation(a5):Play()
end

local a7=g(a3,"Flash")
a_.createparticle("muzzle",a7)


local a8=a4.Model
local a9=g(a8,"SShoot")or g(a8,"Shoot")or g(a8,"Shoot1")
if a9 then
local ba=aD.new("Sound",{
SoundId=a9.Value,
Parent=av,
Volume=0.3,
PlayOnRemove=true
})
aD.DestroyRenderObject(ba)
end


local ba=g(ar.Character.Gun,"Shoot",true)
if ba then
aE.ToUse.ReplicateSound:FireServer(ba,nil,1,aL["Rage/FakeShootType"]=="Normal"and 1 or aL["Rage/FakeShootType"]=="Loud"and X or aL["Rage/FakeShootType"]=="Silent"and 0.1 or 1,nil)
end
aE.ToUse.ReplicateAnimations:FireServer"Fire"
end


aW.GetMultiPoints=function(a3,a4)
local a5=a3.CFrame
local a6=a4*0.15

return{
a5.Position,
(a5*o(a6,0,0)).Position,
(a5*o(-a6,0,0)).Position,
(a5*o(0,a6,0)).Position,
(a5*o(0,-a6,0)).Position,
(a5*o(0,0,a6)).Position,
(a5*o(0,0,-a6)).Position
}
end

aW.ScanOrigin=function(a3,a4)
local a5=ar.Character
if not a5 then return nil,nil end
local a6=g(a5,"Head")
if not a6 then return nil,nil end

local a7=a6.Position
local a8=a3.Position
local a9=l(aq,a3.Parent)
local ba=ay.RageBotCache

if a9 and ba.OriginCache[a9]then
local bb=ba.OriginCache[a9]
if Z()-bb.Time<0.5 then
local bc=a8-bb.Origin
ba.RaycastParams.FilterDescendantsInstances={a5,av}
local bd=E(al,bb.Origin,bc,ba.RaycastParams)
if bd and f(bd.Instance,a3.Parent)then
return bb.Origin,a8
end
end
end

ba.RaycastParams.FilterDescendantsInstances={a5,av}
local bb=a8-a7
local bc=E(al,a7,bb,ba.RaycastParams)

if bc and f(bc.Instance,a3.Parent)then
return a7,a8
end

if aL["Rage/MultiPoint"]then
local bd=aW.GetMultiPoints(a3,aL["Rage/MultiPointScale"]or 1)
for be=2,7 do
bb=bd[be]-a7
bc=E(al,a7,bb,ba.RaycastParams)
if bc and f(bc.Instance,a3.Parent)then
return a7,bd[be]
end
end
end

local bd=aL["Rage/OriginScanRadius"]or 6
local be=S(a4 or 12,20)
local bf=P(360/be)

for bg=1,be do
local bh=bf*bg
local bi=a7+s(U(bh)*bd,0,T(bh)*bd)
local bj={0,4,-4}
for bk=1,3 do
local bl=bi+s(0,bj[bk],0)
bb=a8-bl

ay.RaycastParameter.FilterDescendantsInstances={a5,av}
local bm=E(al,a7,bl-a7,ay.RaycastParameter)

if not bm then
bc=E(al,bl,bb,ba.RaycastParams)
if bc and f(bc.Instance,a3.Parent)then
if a9 then ba.OriginCache[a9]={Origin=bl,Time=Z()}end
return bl,a8
end
end
end
end

return nil,nil
end

aW.FindPoint=function(a3)
local a4=av.CFrame.Position
local a5=ay.RageBotCache
a5.RaycastParams.FilterDescendantsInstances={ar.Character,av}
local a6=a3.Position-a4
local a7=E(al,a4,a6,a5.RaycastParams)

if a7 and f(a7.Instance,a3.Parent)then
return a3.Position
end

if aL["Rage/MultiPoint"]then
local a8=aW.GetMultiPoints(a3,aL["Rage/MultiPointScale"]or 1)
for a9=2,7 do
local ba=a8[a9]
a6=ba-a4
a7=E(al,a4,a6,a5.RaycastParams)
if a7 and f(a7.Instance,a3.Parent)then
return ba
end
end
end
return nil
end

aW.WallBang=function(a3,a4,a5,a6)
local a7=ay.RageBotCache
a5=a5*0.01

if aL["Rage/AutoWall"]==false then
local a8=a4-a3
a7.RaycastParams.FilterDescendantsInstances={ar.Character,av}
local a9=E(al,a3,a8,a7.RaycastParams)

if not a9 or(a9.Instance and a9.Instance.Parent and g(a9.Instance.Parent,"Humanoid"))then
return true,1,0
end
return false,0,0
end

local a8=a4-a3
local a9=a8.Unit
local ba=0
local bb=0
local bc=1
local bd=a3
local be={ar.Character,av}
a7.RaycastParams.FilterDescendantsInstances=be

while true do
local bf=E(al,bd,a4-bd,a7.RaycastParams)
if not bf then
return true,bc,bb
end

local bg=bf.Instance
local bh=bf.Position

if bg.Parent and g(bg.Parent,"Humanoid")then
return true,bc,bb
end

local bi=aX[bg.Material]or 1

if bg.Name=="Grate"then bi=0.1 end
if bg.Name=="nowallbang"then return false,0,bb end

if bg.Transparency==1 or not bg.CanCollide or bg.Name=="Glass"or bg.Name=="Cardboard"
or(aY and f(bg,aY))or(Debris and f(bg,Debris))then
bi=0
end

local bj=bg.Parent
if bj then
if bj.Name=="Hitboxes"then
bi=0
elseif g(bj,"Humanoid")then
bi=0.1
end
end

local bk=g(bg,"PartModifier")
if bk then bi=bk.Value end

if bi>0 then
local bl=RaycastParams.new()
bl.FilterType=Enum.RaycastFilterType.Include
bl.FilterDescendantsInstances={bg}

local bm=20
local bn=E(al,bh+a9*bm,a9*-bm,bl)

local bo
if bn then
bo=bn.Position
else
return false,0,bb
end

ba=ba+(bo-bh).Magnitude*bi
bc=1-ba/a5
bb=bb+1
bd=bo+a9*0.01
else
bd=bh+a9*0.01
end

if ba>=a5 or bb>=a6 or bc<=0 then
return false,0,bb
end

I(be,(bj and bj.Name=="Hitboxes")and bj or bg)
a7.RaycastParams.FilterDescendantsInstances=be
end
end
aW.Think=function()
if not aL["Rage/Enabled"]then
aG.RageBot.Active=nil
return
end

local a3=Z()
local a4=ay.RageBotCache

if a3-a4.LastThink<(1.6666666666666665E-2)then return end
a4.LastThink=a3

if a3-a4.LastCleanup>1 then
J(a4.RaycastResults)
a4.LastCleanup=a3
end

local a5=aG.RageBot.Active
if a5~=nil then
local a6=a5.Player
local a7=a6.Character
local a8=g(a6,"Status")
if not a6 or not a7 or not a8 or a8.Alive.Value~=true or a_.fgun=="none"or a_.fgun.Name=="C4"or g(a_.fgun,"Grenade")or g(a_.fgun,"Stab")or g(a7,"ForceField")or ar.Status.Alive.Value==false then
aG.RageBot.Active=nil
end
end

local a6=aL["Rage/RapidFire"]and aL["Rage/RapidFireTick"]or(a_.fgun~="none"and a_.fgun.FireRate.Value)or 0.1
if a3-aG.RageBot.LastRageBotFired<a6 then return end
if ar.Status.Alive.Value==false then return end

local a7=aW.GetEnemies()

local a8=aG.ForwardTrack.Records
local a9=aG.Backtrack.Records
local ba=a4.Entities

for bb,bc in a8 do
local bd=aq:FindFirstChild(bb)
if not bd or not ba[bd]then
a8[bb]=nil
end
end

for bb,bc in a9 do
local bd=aq:FindFirstChild(bb)
if not bd or not ba[bd]then
a9[bb]=nil
end
end

if#a7==0 then
aG.RageBot.Active=nil
return
end
local bb=av.CFrame.Position local bc=
aL["Rage/AutoWall"]==true and aL["Rage/AutoWallMaxWalls"]*1000 or 4 local bd=
(a_.fgun~="none"and a_.fgun.Penetration.Value)or 100

if aL["Rage/FTrack"]then
local be=aG.ForwardTrack.Records
local bf=(aL["Rage/FTrackTime"]or 100)/1000
for bg=1,#a7 do
local bh=a7[bg]
local bi=ba[bh]
if not bi then continue end
local bj=bi.Head
local bk=bi.Root
local bl=bk.Velocity
local bm=bf
if aL["Rage/FTrackAdaptive"]then bm=bm*(1+((bj.Position-bb).Magnitude/100))end
local bn=bj.Position+(bl*bm)


ay.RaycastParameter.FilterDescendantsInstances={Character,av,bh.Character}
local bo=E(al,bj.Position,bn-bj.Position,ay.RaycastParameter)
if bo then
bn=bo.Position-(bl.Unit*0.1)
end

if not be[bh.Name]then be[bh.Name]={}end
be[bh.Name][1]={Position=bn,Time=a3+bf}
end
end

if aL["Rage/Backtrack"]then
local be=aG.Backtrack.Records
local bf=(aL["Rage/BacktrackTime"]or 200)/1000
for bg=1,#a7 do
local bh=a7[bg]
local bi=ba[bh]
if not bi then continue end
if not be[bh.Name]then be[bh.Name]={}end
local bj=be[bh.Name]
I(bj,1,{Position=bi.Head.Position,Time=a3})
if#bj>1 and a3-bj[#bj].Time>bf then K(bj,#bj)end
end
end

if aL["Rage/TimeOffset"]and aZ.Preparation.Value==true then
do
local be=a2.Value
local bf=_()

if be~=aU.LastValue then
aU.LastValue=be
aU.LastChange=bf
aT.CanRage=false
end

local bg=bf-aU.LastChange
local bh=(be*1000)-(bg*1000)

if bh<(be-1)*1000 then
bh=(be-1)*1000
end

local bi=math.floor(bh)
if not aT.CanRage and bi<=(aL["Rage/TimeOffsetValue"]or 30)then
aT.CanRage=true
end
end
else
aT.CanRage=true
end



if aL["Rage/PrepCheck"]and aZ.Preparation.Value then
aG.RageBot.Active=nil
return
end
if aL["Rage/TimeOffset"]and aT.CanRage==false then
aG.RageBot.Active=nil
return
end

if a_.fgun=="none"then
aG.RageBot.Active=nil
return
end
if a_.fgun.Name=="C4"or g(a_.fgun,"Stab")then
aG.RageBot.Active=nil
return
end
if g(a_.fgun,"Grenade")then
aG.RageBot.Active=nil
return
end local be=

aL["Rage/RapidFire"]and aL["Rage/RapidFireTick"]or a_.fgun.FireRate.Value or 0.1
local bf=Z()

local bg=aL["Rage/AutoWall"]==true and aL["Rage/AutoWallMaxWalls"]*1000 or 4
local bh=a_.fgun.Penetration.Value
local bi=av.CFrame.Position

do
if#a7>1 then
L(a7,function(bj,bk)
local bl=ba[bj]
local bm=ba[bk]
if not bl or not bm or not bl.Root or not bm.Root then return false end
return(bl.Root.Position-bi).Magnitude<(bm.Root.Position-bi).Magnitude
end)
end

local bj=false
local bk=a4.RaycastResults

for bl=1,#a7 do
local bm=a7[bl]
local bn=ba[bm]
if not bn then continue end

local bo=bn.Character
local bp=bn.Head
if not bo or not bp or i(bo,"ForceField")then continue end

local bq,br
local bs=false
local bt=0


local bu=g(bm,"CameraCF")
if bu and ah(bu,"CFrameValue")and aL["Rage/CameraResolver"]then
local bv=bu.Value.Position
local bw,bx=aW.WallBang(bi,bv,bh,bg)

if bw then
bq=bv
br=bi
bt=bx or 1
bs=true
end
end
if not bs then
if aL["Rage/OriginScan"]then
br,bq=aW.ScanOrigin(bp,aL["Rage/OriginMaxScan"]or 20)
else
if bk[bm]then
bq=bk[bm]
br=bi
bs=true
else
bq=aW.FindPoint(bp)
if bq then
br=bi
bk[bm]=bq
end
end
end

if bq and not bs then
local bv=br or bi
local bw,bx=aW.WallBang(bv,bq,bh,bg)

if bw then
bt=bx or 1
bs=true
end
end
end


if not bs and aL["Rage/FTrack"]then
local bv=aG.ForwardTrack.Records
local bw=bv[bm.Name]
if bw and bw[1]then
local bx=bw[1].Position
local by,bz=aW.WallBang(bi,bx,bh,bg)

if by then
bq=bx
br=bi
bt=bz or 1
bs=true
end
end
end


if not bs and aL["Rage/Backtrack"]then
local bv=aG.Backtrack.Records
local bw=bv[bm.Name]
if bw then
local bx=bw[#bw]
if bx then
local by=bx.Position
local bz,bA=aW.WallBang(bi,by,bh,bg)

if bz then
bq=by
br=bi
bt=bA or 1
bs=true
end
end
end
end

if bs then
aG.RageBot.Active={
Player=bm,
Character=bo,
Point=bq,
Origin=br
}

local bv=aL["Rage/NoAutoWallDmgReduction"]and 1 or bt
aW.HitPart(bm,"Head",a_.fgun.Name,bv)

aO.RageBot.Fired:Fire{Player=bm,Position=bq,Origin=br,Damage=bv}

aG.RageBot.LastRageBotFired=bf
aW.FakeShoot()
bj=true

if not aL["Rage/MultiTarget"]then
break
end
end
end

if not bj then
aG.RageBot.Active=nil
end
end
end
aW.KillAll=function()
if not aL["Misc/KillAll"]then return end
if aL["Misc/KillAllTimeOffset"]and aZ.Preparation.Value==true then
do
local a4=a2.Value
local a5=_()

if a4~=aV.LastValue then
aV.LastValue=a4
aV.LastChange=a5
aT.CanKillAll=false
end

local a6=a5-aV.LastChange
local a7=(a4*1000)-(a6*1000)

if a7<(a4-1)*1000 then
a7=(a4-1)*1000
end

local a8=math.floor(a7)
if not aT.CanKillAll and a8<=(aL["Misc/KillAllTimeOffsetValue"]or 30)then
aT.CanKillAll=true
end
end
else
aT.CanKillAll=true
end

if aL["Misc/KillAllTimeOffset"]and aT.CanKillAll==false then return end
if aL["Misc/KillAllPrepCheck"]and aZ.Preparation.Value then return end
if ar.Status.Alive.Value==false then return end

local a4=aW.GetEnemies()
if#a4==0 then return end
for a5=1,#a4 do
local a6=a4[a5]
local a7=a6.Character
if not a7 or not g(a7,"HumanoidRootPart")then
continue
end
if i(a7,"ForceField")then
continue
end
aW.HitPart(a6,"Head","AWP",1)
end
end
local a4
aJ:Connection(am.RenderStepped,function(a5)
ae(aG.Misc.Functions.Movement)
ae(aG.Visuals.Functions.Lighting)
ae(aW.KillAll)
do
local a6=aL["Visuals/ThirdPersonKey"].Active and"Out"or"In"
aG.Visuals.Functions.ThirdPerson(a6)
end

if aG.RageBot.CurrentTarget~=nil then
if aG.RageBot.CurrentTarget~=a4 then
aO.RageBot.TargetChanged:Fire{OldTarget=a4,CurrentTarget=aG.RageBot.CurrentTarget}
end
a4=aG.RageBot.CurrentTarget
end

aW.Think()
end)

end

do
local aT;aT=hookmetamethod(game,"__namecall",function(aU,...)
local aV=getnamecallmethod()
local aW={...}

if aV=="FireServer"then
if aU.Name=="HitParl"then
local aX=aG.Utility.DecodePosition(aW[2])
local aY
if aW[1]and aW[1].Parent and g(aq,aW[1].Parent.Name)then
aY=g(aq,aW[1].Parent.Name)
end
aw(aG.Misc.Functions.HitSound,aW[1].Name or"Head")
if aG.Constants.Hitboxes[aW[1].Name]then

aG.LastHit=aY

if aL["Misc/KillAll"]~=true then
ax(8,aG.Visuals.Functions.Hitmark,aX)
end
ax(8,aG.Visuals.Functions.Hitmark,aX)
ax(8,function()
aO.Events.HitPlayer:Fire{Player=(aY or nil),Position=aX,UsedGun=aW[3],Hitbox=aW[1].Name}
end)
end

if aG.RageBot.Active~=nil or aL["Misc/KillAll"]==true then
aW[2]=au
end
end
if aU.Name=="ApplyGun"then
aw(aG.Misc.Functions.ApplyGunModification)
end
if aU.Name=="ohnoflames"and aL["Misc/NoFireDamage"]then
return
elseif aU.Name=="FallDamage"and aL["Misc/NoFallDamage"]then
return
end

if aU.Name=="RemoteEvent"then
local aX=aW[1]
if type(aX)~="table"then return end

local aY=aX[1]
local aZ=aX[2]

if(ac(aY)=="string"and G(aY)=="kick")
or(ac(aZ)=="string"and H(G(aZ),"error"))then
return
end
end

return aT(aU,M(aW,1,N("#",...)))
end
if aV=="PivotTo"and aU.Name=="Arms"then
local aX=aW[1]

if aL["Visuals/VmOffset"]then
if aX then
local aY=p(ay.ViewmodelOffsetPitch,ay.ViewmodelOffsetYaw,ay.ViewmodelOffsetRoll)
aW[1]=aX*o(ay.ViewmodelOffsetX,ay.ViewmodelOffsetY,ay.ViewmodelOffsetZ)*aY
aX=aX*o(ay.ViewmodelOffsetX,ay.ViewmodelOffsetY,ay.ViewmodelOffsetZ)*aY
end
end
if aL["Rage/RotateVM"]then
do
local aY=aG.RageBot.Active
if aY~=nil and aY.Point then
local aZ=aY.Point

if aX then
aW[1]=q(aX.Position,aZ)
end
end
end
end

if aG.Visuals.States.ThirdPerson=="Out"or aG.Visuals.States.ThirdPerson=="Transitioing_Out"then
aW[1]=o(0,0,0)
end

return aT(aU,M(aW))
end
if aU.Name=="HaIIoooooooooooo"or aU.Name=="Boogers"then
if aV=="FireServer"
or aV=="FireUnreliable"
or aV=="InvokeServer"then
return nil
end
end

return aT(aU,...)
end)

local aU;aU=hookmetamethod(game,"__newindex",function(aV,aW,aX)
if aW=="FieldOfView"then
aX=aL["Visuals/CameraFieldOfView"]
end
return aU(aV,aW,aX)
end)
end

do
aJ:Connection(ar.Status.Kills.Changed,function(aT)
if aT==0 then return end
ae(aG.Misc.Functions.KillSound)
if aG.LastHit~=nil then
if g(aG.LastHit,"Status")and aG.LastHit.Status.Alive.Value~=true then
aO.Events.KillPlayer:Fire{Kills=aT,Player=aG.LastHit}
end
end
end)
end



aJ:ConfigListUpdate()
for aT,aU in aK.Preset do
pcall(function()
aJ:UpdateTheme(aT,aU)
end)
end
ad()
aJ.OldConfig=aJ:GetConfig()

aJ:Notification{text="Loaded Sucessfully."}
aJ:Notification{text="UI Library originally made by Finobe (i77lhm), UI Rewritten by Nam (@mental1illness)"}
